"""Danh sách schema contract: tên thư mục mock / file JSON Schema → model Pydantic."""

from __future__ import annotations

from pydantic import BaseModel

from advertest_contracts.models import (
    AccessRequest,
    ApproveRequest,
    ArtifactUrlRequest,
    ArtifactUrlResponse,
    AttackConfig,
    AttackSpec,
    AuditLogEntry,
    AuditLogPage,
    ClassMapping,
    ClassMappingSummary,
    CleanEvalResult,
    ComputeTargetPublic,
    CostProfile,
    DatasetManifest,
    DatasetSummary,
    DatasetVersionSummary,
    ErrorResponse,
    EstimateResponse,
    ExperimentClone,
    ExperimentConfig,
    ExperimentCreate,
    ExperimentDetail,
    ExperimentPage,
    ExperimentSummary,
    FailureCaseRecord,
    FailureCaseView,
    HealthResponse,
    HeartbeatRequest,
    LoginRequest,
    Manifest,
    Me,
    ModelCard,
    ModelSummary,
    PasswordChange,
    PasswordResetConsume,
    PasswordResetLink,
    ProgressReport,
    ProtocolBody,
    ProtocolSummary,
    RejectRequest,
    RolesUpdate,
    RunCompletion,
    RunResult,
    RunStartRequest,
    RunStartResponse,
    RunView,
    SearchResult,
    SliceSpec,
    SliceSummary,
    UserAdminPage,
    UserAdminView,
    WorkerDirective,
    WorkerJobBundle,
    WorkerLease,
)

SCHEMAS: dict[str, type[BaseModel]] = {
    "attack_spec": AttackSpec,
    "attack_config": AttackConfig,
    "experiment_config": ExperimentConfig,
    "run_result": RunResult,
    "manifest": Manifest,
    "search_result": SearchResult,
    "protocol_body": ProtocolBody,
    "error_response": ErrorResponse,
    "health_response": HealthResponse,
    "dataset_manifest": DatasetManifest,
    "model_card": ModelCard,
    "class_mapping": ClassMapping,
    "slice_spec": SliceSpec,
    "clean_eval_result": CleanEvalResult,
    "failure_case_record": FailureCaseRecord,
    # Phase 3: API nội bộ của worker.
    "cost_profile": CostProfile,
    "worker_lease": WorkerLease,
    "worker_job_bundle": WorkerJobBundle,
    "heartbeat_request": HeartbeatRequest,
    "run_start_request": RunStartRequest,
    "run_start_response": RunStartResponse,
    "progress_report": ProgressReport,
    "worker_directive": WorkerDirective,
    "artifact_url_request": ArtifactUrlRequest,
    "artifact_url_response": ArtifactUrlResponse,
    "run_completion": RunCompletion,
    # Phase 4: xác thực, phân quyền, quản trị người dùng và audit log.
    "access_request": AccessRequest,
    "login_request": LoginRequest,
    "me": Me,
    "user_admin_view": UserAdminView,
    "user_admin_page": UserAdminPage,
    "approve_request": ApproveRequest,
    "reject_request": RejectRequest,
    "roles_update": RolesUpdate,
    "password_change": PasswordChange,
    "password_reset_link": PasswordResetLink,
    "password_reset_consume": PasswordResetConsume,
    "audit_log_entry": AuditLogEntry,
    "audit_log_page": AuditLogPage,
    # Phase 5: wizard, experiment, run, failure case trên web.
    "model_summary": ModelSummary,
    "dataset_summary": DatasetSummary,
    "dataset_version_summary": DatasetVersionSummary,
    "slice_summary": SliceSummary,
    "class_mapping_summary": ClassMappingSummary,
    "protocol_summary": ProtocolSummary,
    "compute_target_public": ComputeTargetPublic,
    "experiment_create": ExperimentCreate,
    "experiment_clone": ExperimentClone,
    "estimate_response": EstimateResponse,
    "experiment_summary": ExperimentSummary,
    "experiment_detail": ExperimentDetail,
    "experiment_page": ExperimentPage,
    "run_view": RunView,
    "failure_case_view": FailureCaseView,
}
