"""Danh sách schema contract: tên thư mục mock / file JSON Schema → model Pydantic."""

from __future__ import annotations

from pydantic import BaseModel

from advertest_contracts.models import (
    AccessRequest,
    ApproveRequest,
    ArtifactUrlRequest,
    ArtifactUrlResponse,
    AttackAdapterInfo,
    AttackConfig,
    AttackSpec,
    AttackSpecAdminPage,
    AttackSpecAdminView,
    AttackSpecCreate,
    AttackSpecMetadata,
    AttackSpecReject,
    AttackSpecView,
    AuditLogEntry,
    AuditLogPage,
    CaseVerdictInput,
    CaseVerdictView,
    ClassMapping,
    ClassMappingSummary,
    CleanEvalResult,
    ComputeTargetPublic,
    CostProfile,
    DatasetManifest,
    DatasetSummary,
    DatasetVersionSummary,
    ErrorResponse,
    EstimateResponse,
    ExperimentClone,
    ExperimentConfig,
    ExperimentCreate,
    ExperimentDetail,
    ExperimentDraftRequest,
    ExperimentInsight,
    ExperimentPage,
    ExperimentPreset,
    ExperimentSummary,
    FailureCaseRecord,
    FailureCaseView,
    HealthResponse,
    HeartbeatRequest,
    LoginRequest,
    Manifest,
    Me,
    ModelCard,
    ModelCheckResult,
    ModelRegister,
    ModelSummary,
    ModelUpload,
    ModelUploadCreate,
    PasswordChange,
    PasswordResetConsume,
    PasswordResetLink,
    PatchArtifact,
    PatchRegistration,
    ProgressReport,
    PromoteRequest,
    ProtocolBody,
    ProtocolCreate,
    ProtocolSummary,
    ProtocolTemplate,
    ProtocolVersionCreate,
    ProtocolView,
    QuickTryCreate,
    QuickTryView,
    RejectRequest,
    ReportDetail,
    ReportDownload,
    ReportSnapshot,
    ReportView,
    ReviewComment,
    ReviewCommentCreate,
    ReviewDecisionInput,
    ReviewQueueItem,
    RolesUpdate,
    RunCompletion,
    RunResult,
    RunSkipRequest,
    RunStartRequest,
    RunStartResponse,
    RunView,
    SearchResult,
    SearchResultReport,
    SearchRunCreate,
    SliceSpec,
    SliceSummary,
    SpecCheckResult,
    SubmitForReview,
    ToolHeartbeat,
    ToolJobBundle,
    ToolJobResult,
    ToolLease,
    UserAdminPage,
    UserAdminView,
    VerifyInfo,
    WorkerDirective,
    WorkerJobBundle,
    WorkerLease,
)

SCHEMAS: dict[str, type[BaseModel]] = {
    "attack_spec": AttackSpec,
    "attack_config": AttackConfig,
    "experiment_config": ExperimentConfig,
    "run_result": RunResult,
    "manifest": Manifest,
    "search_result": SearchResult,
    "protocol_body": ProtocolBody,
    "error_response": ErrorResponse,
    "health_response": HealthResponse,
    "dataset_manifest": DatasetManifest,
    "model_card": ModelCard,
    "class_mapping": ClassMapping,
    "slice_spec": SliceSpec,
    "clean_eval_result": CleanEvalResult,
    "failure_case_record": FailureCaseRecord,
    # Phase 3: API nội bộ của worker.
    "cost_profile": CostProfile,
    "worker_lease": WorkerLease,
    "worker_job_bundle": WorkerJobBundle,
    "heartbeat_request": HeartbeatRequest,
    "run_start_request": RunStartRequest,
    "run_start_response": RunStartResponse,
    "progress_report": ProgressReport,
    "worker_directive": WorkerDirective,
    "artifact_url_request": ArtifactUrlRequest,
    "artifact_url_response": ArtifactUrlResponse,
    "run_completion": RunCompletion,
    # Phase 4: xác thực, phân quyền, quản trị người dùng và audit log.
    "access_request": AccessRequest,
    "login_request": LoginRequest,
    "me": Me,
    "user_admin_view": UserAdminView,
    "user_admin_page": UserAdminPage,
    "approve_request": ApproveRequest,
    "reject_request": RejectRequest,
    "roles_update": RolesUpdate,
    "password_change": PasswordChange,
    "password_reset_link": PasswordResetLink,
    "password_reset_consume": PasswordResetConsume,
    "audit_log_entry": AuditLogEntry,
    "audit_log_page": AuditLogPage,
    # Phase 5: wizard, experiment, run, failure case trên web.
    "model_summary": ModelSummary,
    "dataset_summary": DatasetSummary,
    "dataset_version_summary": DatasetVersionSummary,
    "slice_summary": SliceSummary,
    "class_mapping_summary": ClassMappingSummary,
    "protocol_summary": ProtocolSummary,
    "compute_target_public": ComputeTargetPublic,
    "experiment_create": ExperimentCreate,
    "experiment_clone": ExperimentClone,
    "estimate_response": EstimateResponse,
    "experiment_summary": ExperimentSummary,
    "experiment_detail": ExperimentDetail,
    "experiment_page": ExperimentPage,
    "run_view": RunView,
    "failure_case_view": FailureCaseView,
    # Phase 6: patch, dừng sớm, attack catalog cho admin.
    "patch_artifact": PatchArtifact,
    "patch_registration": PatchRegistration,
    "run_skip_request": RunSkipRequest,
    "attack_spec_admin_view": AttackSpecAdminView,
    "attack_spec_admin_page": AttackSpecAdminPage,
    # Phase 7: tự tìm ngưỡng.
    "search_run_create": SearchRunCreate,
    "search_result_report": SearchResultReport,
    # Phase 8: protocol, gửi duyệt, review, report, xác minh.
    "protocol_create": ProtocolCreate,
    "protocol_version_create": ProtocolVersionCreate,
    "protocol_view": ProtocolView,
    "submit_for_review": SubmitForReview,
    "case_verdict_input": CaseVerdictInput,
    "case_verdict_view": CaseVerdictView,
    "review_decision_input": ReviewDecisionInput,
    "review_comment_create": ReviewCommentCreate,
    "review_comment": ReviewComment,
    "review_queue_item": ReviewQueueItem,
    "report_view": ReportView,
    "report_detail": ReportDetail,
    "report_snapshot": ReportSnapshot,
    "report_download": ReportDownload,
    "verify_info": VerifyInfo,
    # Phase R2: insight, template, preset, catalog và model qua cấu hình, thử nhanh, job công cụ.
    "attack_spec_view": AttackSpecView,
    "attack_spec_create": AttackSpecCreate,
    "attack_spec_metadata": AttackSpecMetadata,
    "attack_spec_reject": AttackSpecReject,
    "attack_adapter_info": AttackAdapterInfo,
    "spec_check_result": SpecCheckResult,
    "model_upload_create": ModelUploadCreate,
    "model_upload": ModelUpload,
    "model_register": ModelRegister,
    "model_check_result": ModelCheckResult,
    "experiment_insight": ExperimentInsight,
    "protocol_template": ProtocolTemplate,
    "experiment_preset": ExperimentPreset,
    "experiment_draft_request": ExperimentDraftRequest,
    "promote_request": PromoteRequest,
    "quick_try_create": QuickTryCreate,
    "quick_try_view": QuickTryView,
    "tool_lease": ToolLease,
    "tool_job_bundle": ToolJobBundle,
    "tool_heartbeat": ToolHeartbeat,
    "tool_job_result": ToolJobResult,
}
