/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Slices */
        get: operations["list_slices_slices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attack-specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attack Specs */
        get: operations["list_attack_specs_attack_specs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protocols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Protocol */
        post: operations["create_protocol_protocols_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failure-cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Failure Case */
        get: operations["get_failure_case_failure_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compute-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Compute Targets */
        get: operations["list_compute_targets_compute_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Log */
        get: operations["list_audit_log_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Report */
        get: operations["verify_report_verify__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lease
         * @description Nhận experiment kế tiếp dành cho máy này.
         */
        post: operations["lease_internal_worker_lease_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_internal_worker_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/runs/{run_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Progress
         * @description Cập nhật tiến độ và checkpoint.
         */
        post: operations["report_progress_internal_worker_runs__run_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/runs/{run_id}/artifact-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Artifact Url
         * @description Xin presigned URL để upload artifact.
         */
        post: operations["artifact_url_internal_worker_runs__run_id__artifact_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/runs/{run_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Run
         * @description Gửi RunResult cuối cùng.
         */
        post: operations["complete_run_internal_worker_runs__run_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/worker/experiments/{experiment_id}/search-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Search Result */
        post: operations["submit_search_result_internal_worker_experiments__experiment_id__search_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttackAccess
         * @enum {string}
         */
        AttackAccess: "white_box" | "black_box";
        /**
         * AttackConfig
         * @description Một attack trong experiment.
         */
        AttackConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /**
             * Spec Sha256
             * @description Chốt đúng version spec
             */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            grid?: components["schemas"]["GridConfig"] | null;
            search?: components["schemas"]["SearchConfig"] | null;
            /** Seed */
            seed: number;
        };
        /**
         * AttackKind
         * @enum {string}
         */
        AttackKind: "attack" | "corruption" | "occlusion";
        /**
         * AttackSpec
         * @description Một attack trong catalog. Đổi bất kỳ trường nào phải tăng `version`.
         */
        AttackSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Name */
            name: string;
            /** Version */
            version: number;
            kind: components["schemas"]["AttackKind"];
            access: components["schemas"]["AttackAccess"];
            /**
             * Art Class
             * @description Null với corruption và occlusion
             */
            art_class?: string | null;
            primary_param: components["schemas"]["PrimaryParam"];
            /** Fixed Params */
            fixed_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            cost_model: components["schemas"]["CostModel"];
            /** Requires Gradients */
            requires_gradients: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Spec Sha256
             * @description Hash của mọi trường trừ id và chính nó
             */
            spec_sha256: string;
        };
        /**
         * CaseSeverity
         * @enum {string}
         */
        CaseSeverity: "critical" | "major" | "minor" | "acceptable";
        /** ClassRunMetrics */
        ClassRunMetrics: {
            /** Clean Ap50 */
            clean_ap50: number | null;
            /** Attacked Ap50 */
            attacked_ap50: number | null;
        };
        /** Cost */
        "Cost-Input": {
            /** Amount */
            amount: number | string;
            /** Currency */
            currency: string;
        };
        /** Cost */
        "Cost-Output": {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** CostModel */
        CostModel: {
            /**
             * Passes Per Image
             * @description Số lần forward + backward cho mỗi ảnh
             */
            passes_per_image?: number | null;
            /**
             * Cpu Only
             * @default false
             */
            cpu_only: boolean;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @description Lý do khi ok = false
             */
            detail?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "not_implemented";
        /**
         * ErrorResponse
         * @description Body lỗi thống nhất của mọi endpoint: {"error": {"code", "message"}}.
         */
        ErrorResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            error: components["schemas"]["ErrorBody"];
        };
        /** ExperimentConfig */
        "ExperimentConfig-Input": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Protocol Id
             * Format: uuid
             */
            protocol_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /**
             * Class Mapping Id
             * Format: uuid
             */
            class_mapping_id: string;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /** Attacks */
            attacks: components["schemas"]["AttackConfig"][];
            limit: components["schemas"]["Limit-Input"];
        };
        /** ExperimentConfig */
        "ExperimentConfig-Output": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Protocol Id
             * Format: uuid
             */
            protocol_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /**
             * Class Mapping Id
             * Format: uuid
             */
            class_mapping_id: string;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /** Attacks */
            attacks: components["schemas"]["AttackConfig"][];
            limit: components["schemas"]["Limit-Output"];
        };
        /** GridConfig */
        GridConfig: {
            /** Levels */
            levels: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Status
             * @description degraded khi có dependency không ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Git Commit */
            git_commit: string;
            postgres: components["schemas"]["DependencyStatus"];
            minio: components["schemas"]["DependencyStatus"];
        };
        JsonValue: unknown;
        /** Limit */
        "Limit-Input": {
            kind: components["schemas"]["LimitKind"];
            /**
             * Value
             * @description Tiền (budget) hoặc giây (time)
             */
            value: number | string;
        };
        /** Limit */
        "Limit-Output": {
            kind: components["schemas"]["LimitKind"];
            /**
             * Value
             * @description Tiền (budget) hoặc giây (time)
             */
            value: string;
        };
        /**
         * LimitKind
         * @enum {string}
         */
        LimitKind: "budget" | "time";
        /** MapPair */
        MapPair: {
            /** Map50 */
            map50: number;
            /** Map50 95 */
            map50_95: number;
        };
        /** PassCriterion */
        PassCriterion: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /** Class Filter */
            class_filter?: string[] | null;
        };
        /** PrimaryParam */
        PrimaryParam: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "continuous" | "discrete";
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Values
             * @description Chỉ dùng khi type = discrete
             */
            values?: number[] | null;
            /** Unit */
            unit: string;
        };
        /** Progress */
        Progress: {
            /** Images Done */
            images_done: number;
            /** Images Total */
            images_total: number;
        };
        /** ProtocolBody */
        ProtocolBody: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Required Attacks */
            required_attacks: components["schemas"]["RequiredAttack"][];
            /** Min Slice Size */
            min_slice_size: number;
            /** Pass Criteria */
            pass_criteria: components["schemas"]["PassCriterion"][];
            /** @description Case từ mức này trở lên bắt buộc có verdict */
            review_severity_threshold: components["schemas"]["CaseSeverity"];
        };
        /** RequiredAttack */
        RequiredAttack: {
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Spec Sha256 */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /** @description Các level tối thiểu phải chạy */
            grid?: components["schemas"]["GridConfig"] | null;
            /** @description Cấu hình tìm kiếm tối thiểu */
            search?: components["schemas"]["SearchConfig"] | null;
        };
        /** RunMetrics */
        RunMetrics: {
            clean: components["schemas"]["MapPair"];
            attacked: components["schemas"]["MapPair"];
            /**
             * Relative Drop
             * @description null khi mAP@0.5 sạch bằng 0
             */
            relative_drop: number | null;
            /** Absolute Drop */
            absolute_drop: number;
            /**
             * Attack Success Rate
             * @description null khi không có object nào được detect đúng trên ảnh sạch (|C| = 0)
             */
            attack_success_rate: number | null;
            /** Per Class */
            per_class?: {
                [key: string]: components["schemas"]["ClassRunMetrics"];
            } | null;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "grid" | "search";
        /** RunResult */
        "RunResult-Input": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            status: components["schemas"]["RunStatus"];
            status_reason?: components["schemas"]["StatusReason"] | null;
            progress: components["schemas"]["Progress"];
            metrics?: components["schemas"]["RunMetrics"] | null;
            /** Gpu Seconds */
            gpu_seconds: number;
            /** @description null với máy local */
            cost?: components["schemas"]["Cost-Input"] | null;
            /** Failure Case Ids */
            failure_case_ids: string[];
            /** Manifest Uri */
            manifest_uri?: string | null;
        };
        /** RunResult */
        "RunResult-Output": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            status: components["schemas"]["RunStatus"];
            status_reason?: components["schemas"]["StatusReason"] | null;
            progress: components["schemas"]["Progress"];
            metrics?: components["schemas"]["RunMetrics"] | null;
            /** Gpu Seconds */
            gpu_seconds: number;
            /** @description null với máy local */
            cost?: components["schemas"]["Cost-Output"] | null;
            /** Failure Case Ids */
            failure_case_ids: string[];
            /** Manifest Uri */
            manifest_uri?: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed" | "skipped" | "stopped_limit" | "cancelled";
        /** SearchConfig */
        SearchConfig: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Tol */
            tol: number;
            /** Coarse N */
            coarse_n: number;
            /** Subset Size */
            subset_size: number;
            /** Class Filter */
            class_filter?: string[] | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            status: components["schemas"]["SearchStatus"];
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /** Breaking Point */
            breaking_point?: number | null;
            /**
             * Bracket
             * @description Khoảng hiện tại, kể cả khi dừng giữa chừng
             */
            bracket: [
                number,
                number
            ];
            /**
             * Confidence Interval
             * @description null nếu chưa tính bootstrap
             */
            confidence_interval?: [
                number,
                number
            ] | null;
            /**
             * Near Threshold
             * @description Khoảng tin cậy bao trùm ngưỡng
             */
            near_threshold: boolean;
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPoint"][];
        };
        /**
         * SearchStatus
         * @enum {string}
         */
        SearchStatus: "found" | "not_reached" | "below_min" | "stopped_limit" | "non_monotonic";
        /**
         * SkipReason
         * @enum {string}
         */
        SkipReason: "cached" | "incompatible";
        /** StatusReason */
        StatusReason: {
            /** Code */
            code: components["schemas"]["StopReason"] | components["schemas"]["SkipReason"] | ("error" | "cancelled");
            /** Message */
            message: string;
        };
        /**
         * StopReason
         * @enum {string}
         */
        StopReason: "budget" | "time";
        /**
         * ThresholdKind
         * @enum {string}
         */
        ThresholdKind: "relative_drop" | "absolute_drop" | "attack_success_rate";
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Order */
            order: number;
            /** Level */
            level: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "subset" | "full";
            /** Drop */
            drop: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AttackAccess = components['schemas']['AttackAccess'];
export type AttackConfig = components['schemas']['AttackConfig'];
export type AttackKind = components['schemas']['AttackKind'];
export type AttackSpec = components['schemas']['AttackSpec'];
export type CaseSeverity = components['schemas']['CaseSeverity'];
export type ClassRunMetrics = components['schemas']['ClassRunMetrics'];
export type CostInput = components['schemas']['Cost-Input'];
export type CostOutput = components['schemas']['Cost-Output'];
export type CostModel = components['schemas']['CostModel'];
export type DependencyStatus = components['schemas']['DependencyStatus'];
export type ErrorBody = components['schemas']['ErrorBody'];
export type ErrorCode = components['schemas']['ErrorCode'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type ExperimentConfigInput = components['schemas']['ExperimentConfig-Input'];
export type ExperimentConfigOutput = components['schemas']['ExperimentConfig-Output'];
export type GridConfig = components['schemas']['GridConfig'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type JsonValue = components['schemas']['JsonValue'];
export type LimitInput = components['schemas']['Limit-Input'];
export type LimitOutput = components['schemas']['Limit-Output'];
export type LimitKind = components['schemas']['LimitKind'];
export type MapPair = components['schemas']['MapPair'];
export type PassCriterion = components['schemas']['PassCriterion'];
export type PrimaryParam = components['schemas']['PrimaryParam'];
export type Progress = components['schemas']['Progress'];
export type ProtocolBody = components['schemas']['ProtocolBody'];
export type RequiredAttack = components['schemas']['RequiredAttack'];
export type RunMetrics = components['schemas']['RunMetrics'];
export type RunMode = components['schemas']['RunMode'];
export type RunResultInput = components['schemas']['RunResult-Input'];
export type RunResultOutput = components['schemas']['RunResult-Output'];
export type RunStatus = components['schemas']['RunStatus'];
export type SearchConfig = components['schemas']['SearchConfig'];
export type SearchResult = components['schemas']['SearchResult'];
export type SearchStatus = components['schemas']['SearchStatus'];
export type SkipReason = components['schemas']['SkipReason'];
export type StatusReason = components['schemas']['StatusReason'];
export type StopReason = components['schemas']['StopReason'];
export type ThresholdKind = components['schemas']['ThresholdKind'];
export type TrajectoryPoint = components['schemas']['TrajectoryPoint'];
export type ValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_slices_slices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_attack_specs_attack_specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackSpec"][];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_protocol_protocols_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProtocolBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_experiment_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentConfig-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_failure_case_failure_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_reviews_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_report_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_compute_targets_compute_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_budget_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_audit_log_audit_log_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_report_verify__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    lease_internal_worker_lease_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentConfig-Output"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    heartbeat_internal_worker_heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    report_progress_internal_worker_runs__run_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Progress"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    artifact_url_internal_worker_runs__run_id__artifact_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    complete_run_internal_worker_runs__run_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunResult-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_search_result_internal_worker_experiments__experiment_id__search_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Chưa cài đặt */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
