/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttackAccess
         * @enum {string}
         */
        AttackAccess: "white_box" | "black_box";
        /**
         * AttackConfig
         * @description Một attack trong experiment.
         */
        AttackConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /**
             * Spec Sha256
             * @description Chốt đúng version spec
             */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /** @default null */
            grid: components["schemas"]["GridConfig"] | null;
            /** @default null */
            search: components["schemas"]["SearchConfig"] | null;
            /** Seed */
            seed: number;
        };
        /**
         * AttackKind
         * @enum {string}
         */
        AttackKind: "attack" | "corruption" | "occlusion";
        /**
         * AttackSpec
         * @description Một attack trong catalog. Đổi bất kỳ trường nào phải tăng `version`.
         */
        AttackSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Name */
            name: string;
            /** Version */
            version: number;
            kind: components["schemas"]["AttackKind"];
            access: components["schemas"]["AttackAccess"];
            /**
             * Art Class
             * @description Null với corruption và occlusion
             * @default null
             */
            art_class: string | null;
            primary_param: components["schemas"]["PrimaryParam"];
            /** Fixed Params */
            fixed_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            cost_model: components["schemas"]["CostModel"];
            /** Requires Gradients */
            requires_gradients: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Spec Sha256
             * @description Hash của mọi trường trừ id và chính nó
             */
            spec_sha256: string;
        };
        /**
         * BillingMode
         * @enum {string}
         */
        BillingMode: "none" | "hourly";
        /**
         * CaseSeverity
         * @enum {string}
         */
        CaseSeverity: "critical" | "major" | "minor" | "acceptable";
        /** ClassRunMetrics */
        ClassRunMetrics: {
            /** Clean Ap50 */
            clean_ap50: number | null;
            /** Attacked Ap50 */
            attacked_ap50: number | null;
        };
        /**
         * ComputeKind
         * @enum {string}
         */
        ComputeKind: "local" | "rented";
        /** Cost */
        Cost: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** CostModel */
        CostModel: {
            /**
             * Passes Per Image
             * @description Số lần forward + backward cho mỗi ảnh
             * @default null
             */
            passes_per_image: number | null;
            /**
             * Cpu Only
             * @default false
             */
            cpu_only: boolean;
        };
        /**
         * Environment
         * @description Máy đã chạy run. Không thuộc fingerprint.
         */
        Environment: {
            /**
             * Compute Target Id
             * @description null khi chạy bằng CLI
             */
            compute_target_id: string | null;
            /**
             * Gpu Model
             * @description null khi chạy trên CPU
             */
            gpu_model: string | null;
            /** Cuda Version */
            cuda_version: string | null;
            /** Driver Version */
            driver_version: string | null;
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Protocol Id
             * Format: uuid
             */
            protocol_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /**
             * Class Mapping Id
             * Format: uuid
             */
            class_mapping_id: string;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /** Attacks */
            attacks: components["schemas"]["AttackConfig"][];
            limit: components["schemas"]["Limit"];
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "draft" | "queued" | "running" | "completed" | "submitted_for_review" | "in_review" | "approved" | "changes_requested" | "rejected" | "cancelled";
        /** FingerprintInputs */
        FingerprintInputs: {
            /** Config Sha256 */
            config_sha256: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /** Slice Sha256 */
            slice_sha256: string;
            /** Attack Spec Sha256 */
            attack_spec_sha256: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Seed */
            seed: number;
            /** Git Commit */
            git_commit: string;
            lib_versions: components["schemas"]["LibVersions"];
            /** Docker Image Digest */
            docker_image_digest: string;
        };
        /** GridConfig */
        GridConfig: {
            /** Levels */
            levels: number[];
        };
        JsonValue: unknown;
        /** LibVersions */
        LibVersions: {
            /** Torch */
            torch: string;
            /** Art */
            art: string;
            /** Ultralytics */
            ultralytics: string;
            /** Torchmetrics */
            torchmetrics: string;
            /** Numpy */
            numpy: string;
        };
        /** Limit */
        Limit: {
            kind: components["schemas"]["LimitKind"];
            /**
             * Value
             * @description Tiền (budget) hoặc giây (time)
             */
            value: string;
        };
        /**
         * LimitKind
         * @enum {string}
         */
        LimitKind: "budget" | "time";
        /** Manifest */
        Manifest: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Fingerprint
             * @description sha256 của fingerprint_inputs đã chuẩn hóa
             */
            fingerprint: string;
            fingerprint_inputs: components["schemas"]["FingerprintInputs"];
            environment: components["schemas"]["Environment"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MapPair */
        MapPair: {
            /** Map50 */
            map50: number;
            /** Map50 95 */
            map50_95: number;
        };
        /** PassCriterion */
        PassCriterion: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /**
             * Class Filter
             * @default null
             */
            class_filter: string[] | null;
        };
        /** PrimaryParam */
        PrimaryParam: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "continuous" | "discrete";
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Values
             * @description Chỉ dùng khi type = discrete
             * @default null
             */
            values: number[] | null;
            /** Unit */
            unit: string;
        };
        /** Progress */
        Progress: {
            /** Images Done */
            images_done: number;
            /** Images Total */
            images_total: number;
        };
        /** ProtocolBody */
        ProtocolBody: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Required Attacks */
            required_attacks: components["schemas"]["RequiredAttack"][];
            /** Min Slice Size */
            min_slice_size: number;
            /** Pass Criteria */
            pass_criteria: components["schemas"]["PassCriterion"][];
            /** @description Case từ mức này trở lên bắt buộc có verdict */
            review_severity_threshold: components["schemas"]["CaseSeverity"];
        };
        /** RequiredAttack */
        RequiredAttack: {
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Spec Sha256 */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /**
             * @description Các level tối thiểu phải chạy
             * @default null
             */
            grid: components["schemas"]["GridConfig"] | null;
            /**
             * @description Cấu hình tìm kiếm tối thiểu
             * @default null
             */
            search: components["schemas"]["SearchConfig"] | null;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "approve" | "changes_requested" | "reject";
        /**
         * Role
         * @enum {string}
         */
        Role: "engineer" | "reviewer" | "admin";
        /** RunMetrics */
        RunMetrics: {
            clean: components["schemas"]["MapPair"];
            attacked: components["schemas"]["MapPair"];
            /**
             * Relative Drop
             * @description null khi mAP@0.5 sạch bằng 0
             */
            relative_drop: number | null;
            /** Absolute Drop */
            absolute_drop: number;
            /** Attack Success Rate */
            attack_success_rate: number;
            /**
             * Per Class
             * @default null
             */
            per_class: {
                [key: string]: components["schemas"]["ClassRunMetrics"];
            } | null;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "grid" | "search";
        /** RunResult */
        RunResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            status: components["schemas"]["RunStatus"];
            /** @default null */
            status_reason: components["schemas"]["StatusReason"] | null;
            progress: components["schemas"]["Progress"];
            /** @default null */
            metrics: components["schemas"]["RunMetrics"] | null;
            /** Gpu Seconds */
            gpu_seconds: number;
            /**
             * @description null với máy local
             * @default null
             */
            cost: components["schemas"]["Cost"] | null;
            /** Failure Case Ids */
            failure_case_ids: string[];
            /**
             * Manifest Uri
             * @default null
             */
            manifest_uri: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed" | "skipped" | "stopped_limit" | "cancelled";
        /** SearchConfig */
        SearchConfig: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Tol */
            tol: number;
            /** Coarse N */
            coarse_n: number;
            /** Subset Size */
            subset_size: number;
            /**
             * Class Filter
             * @default null
             */
            class_filter: string[] | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            status: components["schemas"]["SearchStatus"];
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /**
             * Breaking Point
             * @default null
             */
            breaking_point: number | null;
            /**
             * Bracket
             * @description Khoảng hiện tại, kể cả khi dừng giữa chừng
             */
            bracket: [
                number,
                number
            ];
            /**
             * Confidence Interval
             * @description null nếu chưa tính bootstrap
             * @default null
             */
            confidence_interval: [
                number,
                number
            ] | null;
            /**
             * Near Threshold
             * @description Khoảng tin cậy bao trùm ngưỡng
             */
            near_threshold: boolean;
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPoint"][];
        };
        /**
         * SearchStatus
         * @enum {string}
         */
        SearchStatus: "found" | "not_reached" | "below_min" | "stopped_limit" | "non_monotonic";
        /**
         * SkipReason
         * @enum {string}
         */
        SkipReason: "cached" | "incompatible";
        /** StatusReason */
        StatusReason: {
            /** Code */
            code: components["schemas"]["StopReason"] | components["schemas"]["SkipReason"] | ("error" | "cancelled");
            /** Message */
            message: string;
        };
        /**
         * StopReason
         * @enum {string}
         */
        StopReason: "budget" | "time";
        /**
         * ThresholdKind
         * @enum {string}
         */
        ThresholdKind: "relative_drop" | "absolute_drop" | "attack_success_rate";
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Order */
            order: number;
            /** Level */
            level: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "subset" | "full";
            /** Drop */
            drop: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "pending" | "active" | "rejected" | "disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AttackAccess = components['schemas']['AttackAccess'];
export type AttackConfig = components['schemas']['AttackConfig'];
export type AttackKind = components['schemas']['AttackKind'];
export type AttackSpec = components['schemas']['AttackSpec'];
export type BillingMode = components['schemas']['BillingMode'];
export type CaseSeverity = components['schemas']['CaseSeverity'];
export type ClassRunMetrics = components['schemas']['ClassRunMetrics'];
export type ComputeKind = components['schemas']['ComputeKind'];
export type Cost = components['schemas']['Cost'];
export type CostModel = components['schemas']['CostModel'];
export type Environment = components['schemas']['Environment'];
export type ExperimentConfig = components['schemas']['ExperimentConfig'];
export type ExperimentStatus = components['schemas']['ExperimentStatus'];
export type FingerprintInputs = components['schemas']['FingerprintInputs'];
export type GridConfig = components['schemas']['GridConfig'];
export type JsonValue = components['schemas']['JsonValue'];
export type LibVersions = components['schemas']['LibVersions'];
export type Limit = components['schemas']['Limit'];
export type LimitKind = components['schemas']['LimitKind'];
export type Manifest = components['schemas']['Manifest'];
export type MapPair = components['schemas']['MapPair'];
export type PassCriterion = components['schemas']['PassCriterion'];
export type PrimaryParam = components['schemas']['PrimaryParam'];
export type Progress = components['schemas']['Progress'];
export type ProtocolBody = components['schemas']['ProtocolBody'];
export type RequiredAttack = components['schemas']['RequiredAttack'];
export type ReviewDecision = components['schemas']['ReviewDecision'];
export type Role = components['schemas']['Role'];
export type RunMetrics = components['schemas']['RunMetrics'];
export type RunMode = components['schemas']['RunMode'];
export type RunResult = components['schemas']['RunResult'];
export type RunStatus = components['schemas']['RunStatus'];
export type SearchConfig = components['schemas']['SearchConfig'];
export type SearchResult = components['schemas']['SearchResult'];
export type SearchStatus = components['schemas']['SearchStatus'];
export type SkipReason = components['schemas']['SkipReason'];
export type StatusReason = components['schemas']['StatusReason'];
export type StopReason = components['schemas']['StopReason'];
export type ThresholdKind = components['schemas']['ThresholdKind'];
export type TrajectoryPoint = components['schemas']['TrajectoryPoint'];
export type UserStatus = components['schemas']['UserStatus'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
