/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttackAccess
         * @enum {string}
         */
        AttackAccess: "white_box" | "black_box";
        /**
         * AttackConfig
         * @description Một attack trong experiment.
         */
        AttackConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /**
             * Spec Sha256
             * @description Chốt đúng version spec
             */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /** @default null */
            grid: components["schemas"]["GridConfig"] | null;
            /** @default null */
            search: components["schemas"]["SearchConfig"] | null;
            /** Seed */
            seed: number;
        };
        /**
         * AttackKind
         * @enum {string}
         */
        AttackKind: "attack" | "corruption" | "occlusion";
        /**
         * AttackSpec
         * @description Một attack trong catalog. Đổi bất kỳ trường nào phải tăng `version`.
         */
        AttackSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Name */
            name: string;
            /** Version */
            version: number;
            kind: components["schemas"]["AttackKind"];
            access: components["schemas"]["AttackAccess"];
            /**
             * Art Class
             * @description Null với corruption và occlusion
             * @default null
             */
            art_class: string | null;
            primary_param: components["schemas"]["PrimaryParam"];
            /** Fixed Params */
            fixed_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            cost_model: components["schemas"]["CostModel"];
            /** Requires Gradients */
            requires_gradients: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Spec Sha256
             * @description Hash của mọi trường trừ id và chính nó
             */
            spec_sha256: string;
        };
        /**
         * BillingMode
         * @enum {string}
         */
        BillingMode: "none" | "hourly";
        /** CacheInfo */
        CacheInfo: {
            /** Key */
            key: string;
            /** Hit */
            hit: boolean;
        };
        /**
         * CaseSeverity
         * @enum {string}
         */
        CaseSeverity: "critical" | "major" | "minor" | "acceptable";
        /** ClassEvalMetrics */
        ClassEvalMetrics: {
            /**
             * Ap50
             * @description null khi và chỉ khi num_gt = 0
             */
            ap50: number | null;
            /**
             * Ap50 95
             * @description null khi và chỉ khi num_gt = 0
             */
            ap50_95: number | null;
            /** Num Gt */
            num_gt: number;
        };
        /** ClassMapping */
        ClassMapping: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Preset
             * @description Ví dụ kitti-coco; null khi tự tạo
             */
            preset: string | null;
            /**
             * Classes
             * @description Class gốc → class model; null thành ignore region unmapped:<class>
             */
            classes: {
                [key: string]: string | null;
            };
            /** @description null là không lọc theo độ khó */
            difficulty: components["schemas"]["DifficultyFilter"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mapping Sha256
             * @description Hash của mọi trường trừ id và chính nó
             */
            mapping_sha256: string;
        };
        /** ClassRunMetrics */
        ClassRunMetrics: {
            /** Clean Ap50 */
            clean_ap50: number | null;
            /** Attacked Ap50 */
            attacked_ap50: number | null;
        };
        /**
         * CleanEvalResult
         * @description Kết quả `advertest eval` trên ảnh sạch.
         */
        CleanEvalResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            model: components["schemas"]["EvalModelRef"];
            slice: components["schemas"]["EvalSliceRef"];
            class_mapping: components["schemas"]["EvalMappingRef"];
            inference_params: components["schemas"]["InferenceParams"];
            metrics: components["schemas"]["EvalMetrics"];
            /** Num Images */
            num_images: number;
            cache: components["schemas"]["CacheInfo"];
            timing: components["schemas"]["Timing"];
            /**
             * Device
             * @description Ví dụ cuda:0 (NVIDIA ...) hoặc cpu
             */
            device: string;
            lib_versions: components["schemas"]["LibVersions"];
            /** Git Commit */
            git_commit: string;
        };
        /**
         * ComputeKind
         * @enum {string}
         */
        ComputeKind: "local" | "rented";
        /** ConverterInfo */
        ConverterInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** Cost */
        Cost: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** CostModel */
        CostModel: {
            /**
             * Passes Per Image
             * @description Số lần forward + backward cho mỗi ảnh
             * @default null
             */
            passes_per_image: number | null;
            /**
             * Cpu Only
             * @default false
             */
            cpu_only: boolean;
        };
        /**
         * DatasetManifest
         * @description Manifest dataset nội bộ. Dataset version = sha256_of(manifest).
         */
        DatasetManifest: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Images */
            images: components["schemas"]["ManifestImage"][];
            /** Annotations */
            annotations: components["schemas"]["ManifestAnnotation"][];
            /** Ignore Regions */
            ignore_regions: components["schemas"]["IgnoreRegion"][];
            /** Categories */
            categories: string[];
            source: components["schemas"]["ManifestSource"];
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @description Lý do khi ok = false
             * @default null
             */
            detail: string | null;
        };
        /**
         * DifficultyFilter
         * @description Ngưỡng độ khó (mức Moderate của KITTI: 25, 1, 0.30). Ngưỡng tính cả biên: GT được giữ khi
         *     đạt cả ba điều kiện, không đạt thì thành ignore region `difficulty:<class>`.
         */
        DifficultyFilter: {
            /**
             * Min Height Px
             * @description Giữ khi chiều cao bbox (y2 - y1, pixel ảnh gốc) >= min_height_px
             */
            min_height_px: number;
            /**
             * Max Occluded
             * @description Giữ khi occluded <= max_occluded
             */
            max_occluded: number;
            /**
             * Max Truncated
             * @description Giữ khi truncated <= max_truncated
             */
            max_truncated: number;
        };
        /**
         * Environment
         * @description Máy đã chạy run. Không thuộc fingerprint.
         */
        Environment: {
            /**
             * Compute Target Id
             * @description null khi chạy bằng CLI
             */
            compute_target_id: string | null;
            /**
             * Gpu Model
             * @description null khi chạy trên CPU
             */
            gpu_model: string | null;
            /** Cuda Version */
            cuda_version: string | null;
            /** Driver Version */
            driver_version: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "not_implemented";
        /**
         * ErrorResponse
         * @description Body lỗi thống nhất của mọi endpoint: {"error": {"code", "message"}}.
         */
        ErrorResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            error: components["schemas"]["ErrorBody"];
        };
        /** EvalMappingRef */
        EvalMappingRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mapping Sha256 */
            mapping_sha256: string;
        };
        /** EvalMetrics */
        EvalMetrics: {
            /** Map50 */
            map50: number;
            /** Map50 95 */
            map50_95: number;
            /**
             * Per Class
             * @description Theo class đích
             */
            per_class: {
                [key: string]: components["schemas"]["ClassEvalMetrics"];
            };
        };
        /** EvalModelRef */
        EvalModelRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Weights Sha256 */
            weights_sha256: string;
        };
        /** EvalSliceRef */
        EvalSliceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slice Sha256 */
            slice_sha256: string;
            /** Image Ids Sha256 */
            image_ids_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Protocol Id
             * Format: uuid
             */
            protocol_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /**
             * Class Mapping Id
             * Format: uuid
             */
            class_mapping_id: string;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /** Attacks */
            attacks: components["schemas"]["AttackConfig"][];
            limit: components["schemas"]["Limit"];
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "draft" | "queued" | "running" | "completed" | "submitted_for_review" | "in_review" | "approved" | "changes_requested" | "rejected" | "cancelled";
        /** FingerprintInputs */
        FingerprintInputs: {
            /** Config Sha256 */
            config_sha256: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /** Slice Sha256 */
            slice_sha256: string;
            /** Attack Spec Sha256 */
            attack_spec_sha256: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Seed */
            seed: number;
            /** Git Commit */
            git_commit: string;
            lib_versions: components["schemas"]["LibVersions"];
            /** Docker Image Digest */
            docker_image_digest: string;
        };
        /** GradientCheck */
        GradientCheck: {
            /** Passed */
            passed: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Details
             * @description Lý do khi passed = false
             * @default null
             */
            details: string | null;
        };
        /** GridConfig */
        GridConfig: {
            /** Levels */
            levels: number[];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Status
             * @description degraded khi có dependency không ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Git Commit */
            git_commit: string;
            postgres: components["schemas"]["DependencyStatus"];
            minio: components["schemas"]["DependencyStatus"];
        };
        /** IgnoreRegion */
        IgnoreRegion: {
            /** Image Id */
            image_id: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Source
             * @description Converter chỉ sinh dont_care; unmapped và difficulty sinh ra khi áp mapping
             */
            source: string;
        };
        /** InferenceParams */
        InferenceParams: {
            /** Conf */
            conf: number;
            /** Iou */
            iou: number;
            /** Max Det */
            max_det: number;
            /**
             * Operating Conf
             * @description Ngưỡng dùng cho tỷ lệ tấn công thành công
             */
            operating_conf: number;
            /** Input Size */
            input_size: number;
        };
        JsonValue: unknown;
        /** LibVersions */
        LibVersions: {
            /** Torch */
            torch: string;
            /** Art */
            art: string;
            /** Ultralytics */
            ultralytics: string;
            /** Torchmetrics */
            torchmetrics: string;
            /** Numpy */
            numpy: string;
        };
        /** Limit */
        Limit: {
            kind: components["schemas"]["LimitKind"];
            /**
             * Value
             * @description Tiền (budget) hoặc giây (time)
             */
            value: string;
        };
        /**
         * LimitKind
         * @enum {string}
         */
        LimitKind: "budget" | "time";
        /** Manifest */
        Manifest: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Fingerprint
             * @description sha256 của fingerprint_inputs đã chuẩn hóa
             */
            fingerprint: string;
            fingerprint_inputs: components["schemas"]["FingerprintInputs"];
            environment: components["schemas"]["Environment"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ManifestAnnotation */
        ManifestAnnotation: {
            /** Image Id */
            image_id: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Category
             * @description Class gốc của dataset, phải có trong categories
             */
            category: string;
            /**
             * Attributes
             * @description KITTI: truncated (0-1), occluded (0-3)
             */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ManifestImage */
        ManifestImage: {
            /** Image Id */
            image_id: string;
            /** File Name */
            file_name: string;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Attributes */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ManifestSource */
        ManifestSource: {
            /**
             * Format
             * @enum {string}
             */
            format: "kitti" | "yolo" | "coco";
            /** Split */
            split: string;
            converter: components["schemas"]["ConverterInfo"];
        };
        /** MapPair */
        MapPair: {
            /** Map50 */
            map50: number;
            /** Map50 95 */
            map50_95: number;
        };
        /**
         * ModelCard
         * @description Model đã đăng ký. id = content_id(weights_sha256).
         */
        ModelCard: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Framework
             * @enum {string}
             */
            framework: "ultralytics" | "torchvision";
            /** Architecture */
            architecture: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /**
             * Class Names
             * @description Theo thứ tự index của model
             */
            class_names: string[];
            /** Input Size */
            input_size: number;
            /**
             * Supports Gradients
             * @description Chỉ true khi bài kiểm tra gradient pass
             */
            supports_gradients: boolean;
            gradient_check: components["schemas"]["GradientCheck"];
            lib_versions: components["schemas"]["LibVersions"];
        };
        /** PassCriterion */
        PassCriterion: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /**
             * Class Filter
             * @default null
             */
            class_filter: string[] | null;
        };
        /** PrimaryParam */
        PrimaryParam: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "continuous" | "discrete";
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Values
             * @description Chỉ dùng khi type = discrete
             * @default null
             */
            values: number[] | null;
            /** Unit */
            unit: string;
        };
        /** Progress */
        Progress: {
            /** Images Done */
            images_done: number;
            /** Images Total */
            images_total: number;
        };
        /** ProtocolBody */
        ProtocolBody: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Required Attacks */
            required_attacks: components["schemas"]["RequiredAttack"][];
            /** Min Slice Size */
            min_slice_size: number;
            /** Pass Criteria */
            pass_criteria: components["schemas"]["PassCriterion"][];
            /** @description Case từ mức này trở lên bắt buộc có verdict */
            review_severity_threshold: components["schemas"]["CaseSeverity"];
        };
        /** RequiredAttack */
        RequiredAttack: {
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Spec Sha256 */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /**
             * @description Các level tối thiểu phải chạy
             * @default null
             */
            grid: components["schemas"]["GridConfig"] | null;
            /**
             * @description Cấu hình tìm kiếm tối thiểu
             * @default null
             */
            search: components["schemas"]["SearchConfig"] | null;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "approve" | "changes_requested" | "reject";
        /**
         * Role
         * @enum {string}
         */
        Role: "engineer" | "reviewer" | "admin";
        /** RunMetrics */
        RunMetrics: {
            clean: components["schemas"]["MapPair"];
            attacked: components["schemas"]["MapPair"];
            /**
             * Relative Drop
             * @description null khi mAP@0.5 sạch bằng 0
             */
            relative_drop: number | null;
            /** Absolute Drop */
            absolute_drop: number;
            /** Attack Success Rate */
            attack_success_rate: number;
            /**
             * Per Class
             * @default null
             */
            per_class: {
                [key: string]: components["schemas"]["ClassRunMetrics"];
            } | null;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "grid" | "search";
        /** RunResult */
        RunResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Fingerprint */
            fingerprint: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            status: components["schemas"]["RunStatus"];
            /** @default null */
            status_reason: components["schemas"]["StatusReason"] | null;
            progress: components["schemas"]["Progress"];
            /** @default null */
            metrics: components["schemas"]["RunMetrics"] | null;
            /** Gpu Seconds */
            gpu_seconds: number;
            /**
             * @description null với máy local
             * @default null
             */
            cost: components["schemas"]["Cost"] | null;
            /** Failure Case Ids */
            failure_case_ids: string[];
            /**
             * Manifest Uri
             * @default null
             */
            manifest_uri: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed" | "skipped" | "stopped_limit" | "cancelled";
        /** SearchConfig */
        SearchConfig: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Tol */
            tol: number;
            /** Coarse N */
            coarse_n: number;
            /** Subset Size */
            subset_size: number;
            /**
             * Class Filter
             * @default null
             */
            class_filter: string[] | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            status: components["schemas"]["SearchStatus"];
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /**
             * Breaking Point
             * @default null
             */
            breaking_point: number | null;
            /**
             * Bracket
             * @description Khoảng hiện tại, kể cả khi dừng giữa chừng
             */
            bracket: [
                number,
                number
            ];
            /**
             * Confidence Interval
             * @description null nếu chưa tính bootstrap
             * @default null
             */
            confidence_interval: [
                number,
                number
            ] | null;
            /**
             * Near Threshold
             * @description Khoảng tin cậy bao trùm ngưỡng
             */
            near_threshold: boolean;
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPoint"][];
        };
        /**
         * SearchStatus
         * @enum {string}
         */
        SearchStatus: "found" | "not_reached" | "below_min" | "stopped_limit" | "non_monotonic";
        /**
         * SkipReason
         * @enum {string}
         */
        SkipReason: "cached" | "incompatible";
        /**
         * SliceFilter
         * @description Bộ lọc tự mô tả, không phụ thuộc model hay mapping.
         */
        SliceFilter: {
            /**
             * Classes
             * @description Class gốc được tính, sắp xếp, không trùng
             */
            classes: string[];
            difficulty: components["schemas"]["DifficultyFilter"] | null;
            /**
             * Min Objects
             * @default 1
             */
            min_objects: number;
        };
        /** SliceSpec */
        SliceSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Slice Sha256
             * @description sha256 của dataset_version_sha256, filter, seed, size, image_ids
             */
            slice_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            filter: components["schemas"]["SliceFilter"];
            /** Seed */
            seed: number;
            /** Size */
            size: number;
            /**
             * Image Ids
             * @description Sắp xếp, không trùng, đúng size phần tử
             */
            image_ids: string[];
            /**
             * Image Ids Sha256
             * @description sha256_of(image_ids)
             */
            image_ids_sha256: string;
        };
        /** StatusReason */
        StatusReason: {
            /** Code */
            code: components["schemas"]["StopReason"] | components["schemas"]["SkipReason"] | ("error" | "cancelled");
            /** Message */
            message: string;
        };
        /**
         * StopReason
         * @enum {string}
         */
        StopReason: "budget" | "time";
        /**
         * ThresholdKind
         * @enum {string}
         */
        ThresholdKind: "relative_drop" | "absolute_drop" | "attack_success_rate";
        /** Timing */
        Timing: {
            /** Total S */
            total_s: number;
            /** Sec Per Image */
            sec_per_image: number;
        };
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Order */
            order: number;
            /** Level */
            level: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "subset" | "full";
            /** Drop */
            drop: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "pending" | "active" | "rejected" | "disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AttackAccess = components['schemas']['AttackAccess'];
export type AttackConfig = components['schemas']['AttackConfig'];
export type AttackKind = components['schemas']['AttackKind'];
export type AttackSpec = components['schemas']['AttackSpec'];
export type BillingMode = components['schemas']['BillingMode'];
export type CacheInfo = components['schemas']['CacheInfo'];
export type CaseSeverity = components['schemas']['CaseSeverity'];
export type ClassEvalMetrics = components['schemas']['ClassEvalMetrics'];
export type ClassMapping = components['schemas']['ClassMapping'];
export type ClassRunMetrics = components['schemas']['ClassRunMetrics'];
export type CleanEvalResult = components['schemas']['CleanEvalResult'];
export type ComputeKind = components['schemas']['ComputeKind'];
export type ConverterInfo = components['schemas']['ConverterInfo'];
export type Cost = components['schemas']['Cost'];
export type CostModel = components['schemas']['CostModel'];
export type DatasetManifest = components['schemas']['DatasetManifest'];
export type DependencyStatus = components['schemas']['DependencyStatus'];
export type DifficultyFilter = components['schemas']['DifficultyFilter'];
export type Environment = components['schemas']['Environment'];
export type ErrorBody = components['schemas']['ErrorBody'];
export type ErrorCode = components['schemas']['ErrorCode'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type EvalMappingRef = components['schemas']['EvalMappingRef'];
export type EvalMetrics = components['schemas']['EvalMetrics'];
export type EvalModelRef = components['schemas']['EvalModelRef'];
export type EvalSliceRef = components['schemas']['EvalSliceRef'];
export type ExperimentConfig = components['schemas']['ExperimentConfig'];
export type ExperimentStatus = components['schemas']['ExperimentStatus'];
export type FingerprintInputs = components['schemas']['FingerprintInputs'];
export type GradientCheck = components['schemas']['GradientCheck'];
export type GridConfig = components['schemas']['GridConfig'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type IgnoreRegion = components['schemas']['IgnoreRegion'];
export type InferenceParams = components['schemas']['InferenceParams'];
export type JsonValue = components['schemas']['JsonValue'];
export type LibVersions = components['schemas']['LibVersions'];
export type Limit = components['schemas']['Limit'];
export type LimitKind = components['schemas']['LimitKind'];
export type Manifest = components['schemas']['Manifest'];
export type ManifestAnnotation = components['schemas']['ManifestAnnotation'];
export type ManifestImage = components['schemas']['ManifestImage'];
export type ManifestSource = components['schemas']['ManifestSource'];
export type MapPair = components['schemas']['MapPair'];
export type ModelCard = components['schemas']['ModelCard'];
export type PassCriterion = components['schemas']['PassCriterion'];
export type PrimaryParam = components['schemas']['PrimaryParam'];
export type Progress = components['schemas']['Progress'];
export type ProtocolBody = components['schemas']['ProtocolBody'];
export type RequiredAttack = components['schemas']['RequiredAttack'];
export type ReviewDecision = components['schemas']['ReviewDecision'];
export type Role = components['schemas']['Role'];
export type RunMetrics = components['schemas']['RunMetrics'];
export type RunMode = components['schemas']['RunMode'];
export type RunResult = components['schemas']['RunResult'];
export type RunStatus = components['schemas']['RunStatus'];
export type SearchConfig = components['schemas']['SearchConfig'];
export type SearchResult = components['schemas']['SearchResult'];
export type SearchStatus = components['schemas']['SearchStatus'];
export type SkipReason = components['schemas']['SkipReason'];
export type SliceFilter = components['schemas']['SliceFilter'];
export type SliceSpec = components['schemas']['SliceSpec'];
export type StatusReason = components['schemas']['StatusReason'];
export type StopReason = components['schemas']['StopReason'];
export type ThresholdKind = components['schemas']['ThresholdKind'];
export type Timing = components['schemas']['Timing'];
export type TrajectoryPoint = components['schemas']['TrajectoryPoint'];
export type UserStatus = components['schemas']['UserStatus'];
export type $defs = Record<string, never>;
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const attackAccessValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AttackAccess"]> = ["white_box", "black_box"];
export const attackKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AttackKind"]> = ["attack", "corruption", "occlusion"];
export const billingModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["BillingMode"]> = ["none", "hourly"];
export const caseSeverityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CaseSeverity"]> = ["critical", "major", "minor", "acceptable"];
export const computeKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ComputeKind"]> = ["local", "rented"];
export const errorCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ErrorCode"]> = ["not_implemented"];
export const experimentStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ExperimentStatus"]> = ["draft", "queued", "running", "completed", "submitted_for_review", "in_review", "approved", "changes_requested", "rejected", "cancelled"];
export const healthResponseStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthResponse"]["status"]> = ["ok", "degraded"];
export const limitKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LimitKind"]> = ["budget", "time"];
export const manifestSourceFormatValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ManifestSource"]["format"]> = ["kitti", "yolo", "coco"];
export const modelCardFrameworkValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ModelCard"]["framework"]> = ["ultralytics", "torchvision"];
export const primaryParamTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PrimaryParam"]["type"]> = ["continuous", "discrete"];
export const reviewDecisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ReviewDecision"]> = ["approve", "changes_requested", "reject"];
export const roleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Role"]> = ["engineer", "reviewer", "admin"];
export const runModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RunMode"]> = ["grid", "search"];
export const runStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RunStatus"]> = ["queued", "running", "completed", "failed", "skipped", "stopped_limit", "cancelled"];
export const searchStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SearchStatus"]> = ["found", "not_reached", "below_min", "stopped_limit", "non_monotonic"];
export const skipReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SkipReason"]> = ["cached", "incompatible"];
export const statusReasonCodeAnyOf2Values: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StatusReason"]["code"]> = ["error", "cancelled"];
export const stopReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StopReason"]> = ["budget", "time"];
export const thresholdKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ThresholdKind"]> = ["relative_drop", "absolute_drop", "attack_success_rate"];
export const trajectoryPointScopeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TrajectoryPoint"]["scope"]> = ["subset", "full"];
export const userStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UserStatus"]> = ["pending", "active", "rejected", "disabled"];
export type operations = Record<string, never>;
