/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessRequest */
        AccessRequest: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /**
             * Organization
             * @default null
             */
            organization: string | null;
            requested_role: components["schemas"]["Role"];
            /** Reason */
            reason: string;
            /** Password */
            password: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            /** Roles */
            roles: components["schemas"]["Role"][];
        };
        /** ArtifactUrlRequest */
        ArtifactUrlRequest: {
            /**
             * Lease Id
             * Format: uuid
             */
            lease_id: string;
            /**
             * Key
             * @description Khóa đầy đủ, phải nằm trong runs/<run_id>/
             */
            key: string;
            /**
             * Method
             * @enum {string}
             */
            method: "PUT" | "GET" | "DELETE";
        };
        /** ArtifactUrlResponse */
        ArtifactUrlResponse: {
            /** Key */
            key: string;
            /**
             * Method
             * @enum {string}
             */
            method: "PUT" | "GET" | "DELETE";
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * AttackAccess
         * @enum {string}
         */
        AttackAccess: "white_box" | "black_box";
        /**
         * AttackConfig
         * @description Một attack trong experiment.
         */
        AttackConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /**
             * Spec Sha256
             * @description Chốt đúng version spec
             */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /** @default null */
            grid: components["schemas"]["GridConfig"] | null;
            /** @default null */
            search: components["schemas"]["SearchConfig"] | null;
            /** Seed */
            seed: number;
        };
        /**
         * AttackKind
         * @enum {string}
         */
        AttackKind: "attack" | "corruption" | "occlusion";
        /**
         * AttackSpec
         * @description Một attack trong catalog. Đổi bất kỳ trường nào phải tăng `version`.
         */
        AttackSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Name */
            name: string;
            /** Version */
            version: number;
            kind: components["schemas"]["AttackKind"];
            access: components["schemas"]["AttackAccess"];
            /**
             * Art Class
             * @description Null với corruption và occlusion
             * @default null
             */
            art_class: string | null;
            primary_param: components["schemas"]["PrimaryParam"];
            /** Fixed Params */
            fixed_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            cost_model: components["schemas"]["CostModel"];
            /** Requires Gradients */
            requires_gradients: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Spec Sha256
             * @description Hash của mọi trường trừ id và chính nó
             */
            spec_sha256: string;
        };
        /** AuditActor */
        AuditActor: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
        };
        /** AuditLogEntry */
        AuditLogEntry: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** @description null với hành động của hệ thống */
            actor: components["schemas"]["AuditActor"] | null;
            /**
             * Action
             * @description Theo quy ước `entity.verb` (ví dụ user.approved)
             * @example user.approved
             */
            action: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string | null;
            /** Before */
            before: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** After */
            after: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditLogPage */
        AuditLogPage: {
            /** Items */
            items: components["schemas"]["AuditLogEntry"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * BillingMode
         * @enum {string}
         */
        BillingMode: "none" | "hourly";
        /** BundleCheckpoint */
        BundleCheckpoint: {
            /**
             * Batch Index
             * @description Batch cuối cùng đã xử lý xong
             */
            batch_index: number;
            /** Key */
            key: string;
            /** Url */
            url: string;
        };
        /**
         * BundleDownloads
         * @description Presigned GET URL cho tài nguyên của job.
         */
        BundleDownloads: {
            /** Weights */
            weights: string;
            /** Dataset Manifest */
            dataset_manifest: string;
            /**
             * Images
             * @description image_id → URL, đúng các ảnh của slice
             */
            images: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** BundleLimit */
        BundleLimit: {
            kind: components["schemas"]["LimitKind"];
            /**
             * Value
             * @description Tiền (budget) hoặc giây (time)
             */
            value: string;
            /**
             * Used
             * @description Đã dùng: giây xử lý cộng dồn hoặc tiền
             */
            used: string;
        };
        /** BundleRun */
        BundleRun: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            /** Seed */
            seed: number;
            status: components["schemas"]["RunStatus"];
            /** Images Done */
            images_done: number;
            /** Images Total */
            images_total: number;
            /** @description Checkpoint mới nhất khi đang chạy dở */
            checkpoint: components["schemas"]["BundleCheckpoint"] | null;
        };
        /** CacheInfo */
        CacheInfo: {
            /** Key */
            key: string;
            /** Hit */
            hit: boolean;
        };
        /**
         * CaseArtifacts
         * @description Khóa lưu trữ (LocalStore ở Phase 2, MinIO từ Phase 3) của ảnh PNG letterbox.
         */
        CaseArtifacts: {
            /** Clean Png */
            clean_png: string;
            /** Adversarial Png */
            adversarial_png: string;
            /**
             * Perturbation Png
             * @description Ảnh nhiễu khuếch đại
             */
            perturbation_png: string;
            /**
             * Clean Thumb
             * @description Thumbnail WebP rộng 320 px (Phase 3); null khi chạy bằng CLI, bắt buộc qua worker
             * @default null
             */
            clean_thumb: string | null;
            /**
             * Adversarial Thumb
             * @description Thumbnail WebP rộng 320 px (Phase 3); null khi chạy bằng CLI, bắt buộc qua worker
             * @default null
             */
            adversarial_thumb: string | null;
        };
        /**
         * CaseBox
         * @description Box trong failure case: xyxy pixel trong không gian letterbox.
         */
        CaseBox: {
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Class Name
             * @description Class đích của mapping
             */
            class_name: string;
            /**
             * Score
             * @description null với ground truth, bắt buộc với prediction
             */
            score: number | null;
        };
        /** CaseDetections */
        CaseDetections: {
            /** Ground Truth */
            ground_truth: components["schemas"]["CaseBox"][];
            /** Clean */
            clean: components["schemas"]["CaseBox"][];
            /** Attacked */
            attacked: components["schemas"]["CaseBox"][];
            /** Ignore Regions */
            ignore_regions: components["schemas"]["CaseIgnoreRegion"][];
        };
        /** CaseIgnoreRegion */
        CaseIgnoreRegion: {
            /**
             * Bbox
             * @description xyxy pixel trong không gian letterbox
             */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Source */
            source: string;
        };
        /**
         * CaseSeverity
         * @enum {string}
         */
        CaseSeverity: "critical" | "major" | "minor" | "acceptable";
        /** ClassEvalMetrics */
        ClassEvalMetrics: {
            /**
             * Ap50
             * @description null khi và chỉ khi num_gt = 0
             */
            ap50: number | null;
            /**
             * Ap50 95
             * @description null khi và chỉ khi num_gt = 0
             */
            ap50_95: number | null;
            /** Num Gt */
            num_gt: number;
        };
        /** ClassMapping */
        ClassMapping: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Preset
             * @description Ví dụ kitti-coco; null khi tự tạo
             */
            preset: string | null;
            /**
             * Classes
             * @description Class gốc → class model; null thành ignore region unmapped:<class>
             */
            classes: {
                [key: string]: string | null;
            };
            /** @description null là không lọc theo độ khó */
            difficulty: components["schemas"]["DifficultyFilter"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mapping Sha256
             * @description Hash của mọi trường trừ id và chính nó
             */
            mapping_sha256: string;
        };
        /** ClassMappingSummary */
        ClassMappingSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dataset Version Id
             * Format: uuid
             */
            dataset_version_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /** Mapping Sha256 */
            mapping_sha256: string;
            /** Preset */
            preset: string | null;
            /**
             * Classes
             * @description Class gốc → class model; null là bỏ
             */
            classes: {
                [key: string]: string | null;
            };
        };
        /** ClassRunMetrics */
        ClassRunMetrics: {
            /** Clean Ap50 */
            clean_ap50: number | null;
            /** Attacked Ap50 */
            attacked_ap50: number | null;
        };
        /**
         * CleanEvalResult
         * @description Kết quả `advertest eval` trên ảnh sạch.
         */
        CleanEvalResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            model: components["schemas"]["EvalModelRef"];
            slice: components["schemas"]["EvalSliceRef"];
            class_mapping: components["schemas"]["EvalMappingRef"];
            inference_params: components["schemas"]["InferenceParams"];
            metrics: components["schemas"]["EvalMetrics"];
            /** Num Images */
            num_images: number;
            cache: components["schemas"]["CacheInfo"];
            timing: components["schemas"]["Timing"];
            /**
             * Device
             * @description Ví dụ cuda:0 (NVIDIA ...) hoặc cpu
             */
            device: string;
            lib_versions: components["schemas"]["LibVersions"];
            /** Git Commit */
            git_commit: string;
        };
        /** CloneWarning */
        CloneWarning: {
            /**
             * Attack Spec Id
             * Format: uuid
             * @description ID của spec ở version hiện hành (trong config)
             */
            attack_spec_id: string;
            /** From Version */
            from_version: number;
            /** To Version */
            to_version: number;
            /** Message */
            message: string;
        };
        /**
         * ComputeKind
         * @enum {string}
         */
        ComputeKind: "local" | "rented";
        /** ComputeTargetPublic */
        ComputeTargetPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["ComputeKind"];
            /**
             * Gpu Model
             * @description null với máy chỉ có CPU
             */
            gpu_model: string | null;
            /**
             * Online
             * @description Có heartbeat trong 60 giây gần nhất
             */
            online: boolean;
            /**
             * Queue Length
             * @description Số experiment đang queued trên target
             */
            queue_length: number;
            /** Default Time Limit S */
            default_time_limit_s: number;
            /** Max Time Limit S */
            max_time_limit_s: number;
        };
        /** ComputeTargetRef */
        ComputeTargetRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["ComputeKind"];
        };
        /** ConverterInfo */
        ConverterInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** Cost */
        Cost: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
        };
        /** CostModel */
        CostModel: {
            /**
             * Passes Per Image
             * @description Số lần forward + backward cho mỗi ảnh
             * @default null
             */
            passes_per_image: number | null;
            /**
             * Cpu Only
             * @default false
             */
            cpu_only: boolean;
        };
        /**
         * CostProfile
         * @description Chi phí đo bằng calibration, riêng cho từng (compute target, model, attack).
         */
        CostProfile: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Sec Per Image */
            sec_per_image: number;
            /**
             * Peak Vram Mb
             * @description 0 khi chạy trên CPU
             */
            peak_vram_mb: number;
            /** Batch Size */
            batch_size: number;
            /**
             * Measured At
             * Format: date-time
             */
            measured_at: string;
            environment: components["schemas"]["Environment"];
        };
        /**
         * DatasetManifest
         * @description Manifest dataset nội bộ. Dataset version = sha256_of(manifest).
         */
        DatasetManifest: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Images */
            images: components["schemas"]["ManifestImage"][];
            /** Annotations */
            annotations: components["schemas"]["ManifestAnnotation"][];
            /** Ignore Regions */
            ignore_regions: components["schemas"]["IgnoreRegion"][];
            /** Categories */
            categories: string[];
            source: components["schemas"]["ManifestSource"];
        };
        /** DatasetSummary */
        DatasetSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Anonymized
             * @description false: ảnh bị ẩn trên giao diện cho tới Phase 10
             */
            anonymized: boolean;
            /**
             * Versions
             * @description Mới nhất trước
             */
            versions: components["schemas"]["DatasetVersionSummary"][];
        };
        /** DatasetVersionSummary */
        DatasetVersionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Num Images */
            num_images: number;
            /** Class Names */
            class_names: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DependencyStatus */
        DependencyStatus: {
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @description Lý do khi ok = false
             * @default null
             */
            detail: string | null;
        };
        /**
         * DifficultyFilter
         * @description Ngưỡng độ khó (mức Moderate của KITTI: 25, 1, 0.30). Ngưỡng tính cả biên: GT được giữ khi
         *     đạt cả ba điều kiện, không đạt thì thành ignore region `difficulty:<class>`.
         */
        DifficultyFilter: {
            /**
             * Min Height Px
             * @description Giữ khi chiều cao bbox (y2 - y1, pixel ảnh gốc) >= min_height_px
             */
            min_height_px: number;
            /**
             * Max Occluded
             * @description Giữ khi occluded <= max_occluded
             */
            max_occluded: number;
            /**
             * Max Truncated
             * @description Giữ khi truncated <= max_truncated
             */
            max_truncated: number;
        };
        /**
         * DisplayMode
         * @description Cách hiển thị ảnh failure case (Phase 5, tạm thời đến khi có làm mờ ở Phase 10).
         * @enum {string}
         */
        DisplayMode: "normal" | "hidden_unanonymized" | "dev_unblurred";
        /**
         * Environment
         * @description Máy đã chạy run. Không thuộc fingerprint.
         */
        Environment: {
            /**
             * Compute Target Id
             * @description null khi chạy bằng CLI
             */
            compute_target_id: string | null;
            /**
             * Gpu Model
             * @description null khi chạy trên CPU
             */
            gpu_model: string | null;
            /** Cuda Version */
            cuda_version: string | null;
            /** Driver Version */
            driver_version: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /**
             * Fields
             * @description Chỉ có ở lỗi 422 gắn được với trường cụ thể; không có thì bỏ khỏi body
             * @default null
             */
            fields: components["schemas"]["FieldError"][] | null;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "not_implemented" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "invalid_request" | "invalid_credentials" | "account_pending" | "account_rejected" | "account_disabled" | "rate_limited" | "csrf_failed" | "validation_error" | "not_supported_yet" | "queue_limit_reached" | "internal_error";
        /**
         * ErrorResponse
         * @description Body lỗi thống nhất của mọi endpoint: {"error": {"code", "message"}}.
         */
        ErrorResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            error: components["schemas"]["ErrorBody"];
        };
        /** EstimateResponse */
        EstimateResponse: {
            /** Runs */
            runs: components["schemas"]["EstimateRun"][];
            /**
             * Total Seconds
             * @description null khi có run thiếu profile
             */
            total_seconds: number | null;
            /**
             * Missing Profiles
             * @description attack_spec_id thiếu cost profile, không trùng
             */
            missing_profiles: string[];
            /**
             * Exceeds Limit
             * @description Tổng ước lượng của các run ước lượng được (cận dưới khi thiếu profile) lớn hơn giới hạn thời gian
             */
            exceeds_limit: boolean;
            queue: components["schemas"]["QueueEstimate"];
        };
        /** EstimateRun */
        EstimateRun: {
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            /** Images */
            images: number;
            /**
             * Sec Per Image
             * @description null khi thiếu cost profile
             */
            sec_per_image: number | null;
            /**
             * Est Seconds
             * @description images * sec_per_image * 1.2; null khi thiếu profile; 0 khi run sẽ bị bỏ qua
             */
            est_seconds: number | null;
            /**
             * Skip Reason
             * @description Run sẽ bị `skipped`: attack cần gradient, model không hỗ trợ
             */
            skip_reason: "incompatible" | null;
        };
        /** EvalMappingRef */
        EvalMappingRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mapping Sha256 */
            mapping_sha256: string;
        };
        /** EvalMetrics */
        EvalMetrics: {
            /** Map50 */
            map50: number;
            /** Map50 95 */
            map50_95: number;
            /**
             * Per Class
             * @description Theo class đích
             */
            per_class: {
                [key: string]: components["schemas"]["ClassEvalMetrics"];
            };
        };
        /** EvalModelRef */
        EvalModelRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Weights Sha256 */
            weights_sha256: string;
        };
        /** EvalSliceRef */
        EvalSliceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slice Sha256 */
            slice_sha256: string;
            /** Image Ids Sha256 */
            image_ids_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
        };
        /**
         * ExperimentClone
         * @description `GET /experiments/{id}/clone`: cấu hình điền sẵn; spec cũ đã lên version hiện hành.
         */
        ExperimentClone: {
            config: components["schemas"]["ExperimentCreate"];
            /** Warnings */
            warnings: components["schemas"]["CloneWarning"][];
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Protocol Id
             * Format: uuid
             */
            protocol_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /**
             * Class Mapping Id
             * Format: uuid
             */
            class_mapping_id: string;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /** Attacks */
            attacks: components["schemas"]["AttackConfig"][];
            limit: components["schemas"]["Limit"];
        };
        /**
         * ExperimentCreate
         * @description Body của `POST /experiments` và `POST /experiments/estimate`.
         */
        ExperimentCreate: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Protocol Id
             * Format: uuid
             */
            protocol_id: string;
            /**
             * Model Version Id
             * Format: uuid
             */
            model_version_id: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /**
             * Class Mapping Id
             * Format: uuid
             */
            class_mapping_id: string;
            /**
             * Compute Target Id
             * Format: uuid
             */
            compute_target_id: string;
            /** Attacks */
            attacks: components["schemas"]["AttackConfig"][];
            limit: components["schemas"]["Limit"];
            /**
             * Name
             * @description Bỏ trống: server đặt `<model> · <slice> · <YYYY-MM-DD UTC>`
             * @default null
             */
            name: string | null;
            /**
             * Cloned From
             * @description Experiment gốc khi nhân bản
             * @default null
             */
            cloned_from: string | null;
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            owner: components["schemas"]["UserRef"];
            status: components["schemas"]["ExperimentStatus"];
            model: components["schemas"]["ModelRef"];
            slice: components["schemas"]["SliceRef"];
            compute_target: components["schemas"]["ComputeTargetRef"];
            run_counts: components["schemas"]["RunCounts"];
            /** @description Tổng số ảnh đã xử lý trên mọi run */
            progress: components["schemas"]["Progress"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Finished At
             * @description null khi draft, queued hoặc running
             */
            finished_at: string | null;
            config: components["schemas"]["ExperimentConfig"];
            /** Config Sha256 */
            config_sha256: string;
            protocol: components["schemas"]["ProtocolRef"];
            limit: components["schemas"]["Limit"];
            /** Processing Seconds Used */
            processing_seconds_used: number;
            /**
             * Queue Position
             * @description Chỉ có khi status = queued
             */
            queue_position: number | null;
            /** Cloned From */
            cloned_from: string | null;
            /** @description mAP ảnh sạch; null khi chưa run nào có metric */
            clean_metrics: components["schemas"]["MapPair"] | null;
        };
        /** ExperimentPage */
        ExperimentPage: {
            /** Items */
            items: components["schemas"]["ExperimentSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ExperimentStatus
         * @enum {string}
         */
        ExperimentStatus: "draft" | "queued" | "running" | "completed" | "submitted_for_review" | "in_review" | "approved" | "changes_requested" | "rejected" | "cancelled";
        /** ExperimentSummary */
        ExperimentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            owner: components["schemas"]["UserRef"];
            status: components["schemas"]["ExperimentStatus"];
            model: components["schemas"]["ModelRef"];
            slice: components["schemas"]["SliceRef"];
            compute_target: components["schemas"]["ComputeTargetRef"];
            run_counts: components["schemas"]["RunCounts"];
            /** @description Tổng số ảnh đã xử lý trên mọi run */
            progress: components["schemas"]["Progress"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Finished At
             * @description null khi draft, queued hoặc running
             */
            finished_at: string | null;
        };
        /**
         * FailureCaseRecord
         * @description Một ảnh bị attack làm hỏng nặng trong một run (Phase 2).
         */
        FailureCaseRecord: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Id
             * Format: uuid
             * @description compute_failure_case_id(fingerprint, run_id, image_id)
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Fingerprint
             * @description Fingerprint của run
             */
            fingerprint: string;
            /** Image Id */
            image_id: string;
            /**
             * Lost Objects
             * @description Số object bị mất sau tấn công
             */
            lost_objects: number;
            /**
             * New False Positives
             * @description Số detection sai mới xuất hiện
             */
            new_false_positives: number;
            /**
             * Severity Score
             * @description lost_objects + 0.5 * new_false_positives; chỉ lưu case > 0
             */
            severity_score: number;
            detections: components["schemas"]["CaseDetections"];
            artifacts: components["schemas"]["CaseArtifacts"];
        };
        /**
         * FailureCaseUrls
         * @description URL tạm thời của từng artifact; null khi không cấp (ảnh bị ẩn, hoặc danh sách chỉ có
         *     thumbnail).
         */
        FailureCaseUrls: {
            /** Clean */
            clean: string | null;
            /** Adversarial */
            adversarial: string | null;
            /** Perturbation */
            perturbation: string | null;
            /** Clean Thumb */
            clean_thumb: string | null;
            /** Adversarial Thumb */
            adversarial_thumb: string | null;
        };
        /** FailureCaseView */
        FailureCaseView: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Id
             * Format: uuid
             * @description compute_failure_case_id(fingerprint, run_id, image_id)
             */
            id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Fingerprint
             * @description Fingerprint của run
             */
            fingerprint: string;
            /** Image Id */
            image_id: string;
            /**
             * Lost Objects
             * @description Số object bị mất sau tấn công
             */
            lost_objects: number;
            /**
             * New False Positives
             * @description Số detection sai mới xuất hiện
             */
            new_false_positives: number;
            /**
             * Severity Score
             * @description lost_objects + 0.5 * new_false_positives; chỉ lưu case > 0
             */
            severity_score: number;
            detections: components["schemas"]["CaseDetections"];
            artifacts: components["schemas"]["CaseArtifacts"];
            urls: components["schemas"]["FailureCaseUrls"];
            /**
             * Urls Expire At
             * @description null khi display_mode = hidden_unanonymized
             */
            urls_expire_at: string | null;
            display_mode: components["schemas"]["DisplayMode"];
        };
        /**
         * FieldError
         * @description Lỗi của một trường (Phase 5): giao diện hiển thị tại đúng bước và đúng trường.
         */
        FieldError: {
            /**
             * Path
             * @description Đường dẫn trường trong body, các đoạn ngăn bởi dấu chấm, chỉ số mảng từ 0
             * @example attacks.0.grid.levels
             */
            path: string;
            /** Message */
            message: string;
        };
        /** FingerprintInputs */
        FingerprintInputs: {
            /** Config Sha256 */
            config_sha256: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            /**
             * Slice Id
             * Format: uuid
             */
            slice_id: string;
            /** Slice Sha256 */
            slice_sha256: string;
            /** Attack Spec Sha256 */
            attack_spec_sha256: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Seed */
            seed: number;
            /** Git Commit */
            git_commit: string;
            /**
             * Git Dirty
             * @description Working tree có thay đổi chưa commit lúc chạy
             */
            git_dirty: boolean;
            lib_versions: components["schemas"]["LibVersions"];
            /** Docker Image Digest */
            docker_image_digest: string;
        };
        /** GradientCheck */
        GradientCheck: {
            /** Passed */
            passed: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Details
             * @description Lý do khi passed = false
             * @default null
             */
            details: string | null;
        };
        /** GridConfig */
        GridConfig: {
            /** Levels */
            levels: number[];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Status
             * @description degraded khi có dependency không ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Git Commit */
            git_commit: string;
            postgres: components["schemas"]["DependencyStatus"];
            minio: components["schemas"]["DependencyStatus"];
        };
        /** HeartbeatRequest */
        HeartbeatRequest: {
            /**
             * Lease Id
             * Format: uuid
             */
            lease_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
        };
        /** IgnoreRegion */
        IgnoreRegion: {
            /** Image Id */
            image_id: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Source
             * @description Converter chỉ sinh dont_care; unmapped và difficulty sinh ra khi áp mapping
             */
            source: string;
        };
        /** InferenceParams */
        InferenceParams: {
            /** Conf */
            conf: number;
            /** Iou */
            iou: number;
            /** Max Det */
            max_det: number;
            /**
             * Operating Conf
             * @description Ngưỡng dùng cho tỷ lệ tấn công thành công
             */
            operating_conf: number;
            /** Input Size */
            input_size: number;
        };
        JsonValue: unknown;
        /** LibVersions */
        LibVersions: {
            /** Torch */
            torch: string;
            /** Art */
            art: string;
            /** Ultralytics */
            ultralytics: string;
            /** Torchmetrics */
            torchmetrics: string;
            /** Numpy */
            numpy: string;
        };
        /** Limit */
        Limit: {
            kind: components["schemas"]["LimitKind"];
            /**
             * Value
             * @description Tiền (budget) hoặc giây (time)
             */
            value: string;
        };
        /**
         * LimitKind
         * @enum {string}
         */
        LimitKind: "budget" | "time";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Manifest */
        Manifest: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Fingerprint
             * @description sha256 của fingerprint_inputs đã chuẩn hóa
             */
            fingerprint: string;
            fingerprint_inputs: components["schemas"]["FingerprintInputs"];
            environment: components["schemas"]["Environment"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ManifestAnnotation */
        ManifestAnnotation: {
            /** Image Id */
            image_id: string;
            /** Bbox */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /**
             * Category
             * @description Class gốc của dataset, phải có trong categories
             */
            category: string;
            /**
             * Attributes
             * @description KITTI: truncated (0-1), occluded (0-3)
             */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ManifestImage */
        ManifestImage: {
            /** Image Id */
            image_id: string;
            /** File Name */
            file_name: string;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Attributes */
            attributes?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ManifestSource */
        ManifestSource: {
            /**
             * Format
             * @enum {string}
             */
            format: "kitti" | "yolo" | "coco";
            /** Split */
            split: string;
            converter: components["schemas"]["ConverterInfo"];
        };
        /** MapPair */
        MapPair: {
            /** Map50 */
            map50: number;
            /** Map50 95 */
            map50_95: number;
        };
        /** Me */
        Me: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /**
             * Permissions
             * @description Hợp các permission của mọi role
             */
            permissions: components["schemas"]["Permission"][];
            status: components["schemas"]["UserStatus"];
        };
        /**
         * ModelCard
         * @description Model đã đăng ký. id = content_id(weights_sha256).
         */
        ModelCard: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Framework
             * @enum {string}
             */
            framework: "ultralytics" | "torchvision";
            /** Architecture */
            architecture: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /**
             * Class Names
             * @description Theo thứ tự index của model
             */
            class_names: string[];
            /** Input Size */
            input_size: number;
            /**
             * Supports Gradients
             * @description Chỉ true khi bài kiểm tra gradient pass
             */
            supports_gradients: boolean;
            gradient_check: components["schemas"]["GradientCheck"];
            lib_versions: components["schemas"]["LibVersions"];
        };
        /** ModelRef */
        ModelRef: {
            /**
             * Id
             * Format: uuid
             * @description ID của model version
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ModelSummary */
        ModelSummary: {
            /**
             * Id
             * Format: uuid
             * @description ID của model version
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Framework
             * @description Ví dụ ultralytics; hiển thị ở ô kiến trúc của wizard
             */
            framework: string;
            /** Weights Sha256 */
            weights_sha256: string;
            /** Class Names */
            class_names: string[];
            /** Input Size */
            input_size: number;
            /** Supports Gradients */
            supports_gradients: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PassCriterion */
        PassCriterion: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /**
             * Class Filter
             * @default null
             */
            class_filter: string[] | null;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetConsume */
        PasswordResetConsume: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetLink */
        PasswordResetLink: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "experiment.read" | "experiment.create" | "experiment.cancel_own" | "experiment.submit_review" | "dataset.read" | "dataset.upload" | "slice.create" | "model.read" | "model.manage" | "attack_catalog.read" | "attack_catalog.manage" | "protocol.read" | "protocol.manage" | "review.decide" | "report.export" | "report.read" | "user.manage" | "compute_target.read" | "compute_target.manage" | "budget.manage" | "audit.read";
        /** PrimaryParam */
        PrimaryParam: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "continuous" | "discrete";
            /** Min */
            min: number;
            /** Max */
            max: number;
            /**
             * Values
             * @description Chỉ dùng khi type = discrete
             * @default null
             */
            values: number[] | null;
            /** Unit */
            unit: string;
        };
        /** Progress */
        Progress: {
            /** Images Done */
            images_done: number;
            /** Images Total */
            images_total: number;
        };
        /** ProgressReport */
        ProgressReport: {
            /**
             * Lease Id
             * Format: uuid
             */
            lease_id: string;
            /**
             * Images Done
             * @description Tổng số ảnh đã xử lý của run
             */
            images_done: number;
            /** Batch Index */
            batch_index: number;
            /** Checkpoint Key */
            checkpoint_key: string;
            /**
             * Processing Seconds Delta
             * @description Thời gian xử lý từ lần báo trước; API cộng dồn
             */
            processing_seconds_delta: number;
        };
        /** ProtocolBody */
        ProtocolBody: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Required Attacks */
            required_attacks: components["schemas"]["RequiredAttack"][];
            /** Min Slice Size */
            min_slice_size: number;
            /** Pass Criteria */
            pass_criteria: components["schemas"]["PassCriterion"][];
            /** @description Case từ mức này trở lên bắt buộc có verdict */
            review_severity_threshold: components["schemas"]["CaseSeverity"];
        };
        /** ProtocolRef */
        ProtocolRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ProtocolStatus"];
        };
        /**
         * ProtocolStatus
         * @enum {string}
         */
        ProtocolStatus: "active" | "retired" | "dev";
        /** ProtocolSummary */
        ProtocolSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            status: components["schemas"]["ProtocolStatus"];
            /** Body Sha256 */
            body_sha256: string;
        };
        /** QueueEstimate */
        QueueEstimate: {
            /**
             * Position
             * @description Vị trí của experiment mới trong hàng đợi của target
             */
            position: number;
            /**
             * Ahead Seconds
             * @description Tổng ước lượng còn lại của các experiment đứng trước (bỏ phần không ước lượng được)
             */
            ahead_seconds: number;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Reason */
            reason: string;
        };
        /** RequiredAttack */
        RequiredAttack: {
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Spec Sha256 */
            spec_sha256: string;
            mode: components["schemas"]["RunMode"];
            /**
             * @description Các level tối thiểu phải chạy
             * @default null
             */
            grid: components["schemas"]["GridConfig"] | null;
            /**
             * @description Cấu hình tìm kiếm tối thiểu
             * @default null
             */
            search: components["schemas"]["SearchConfig"] | null;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "approve" | "changes_requested" | "reject";
        /**
         * Role
         * @enum {string}
         */
        Role: "engineer" | "reviewer" | "admin";
        /** RolesUpdate */
        RolesUpdate: {
            /**
             * Roles
             * @description Ít nhất 1 role; muốn chặn truy cập thì vô hiệu hóa
             */
            roles: components["schemas"]["Role"][];
        };
        /** RunAttackSpec */
        RunAttackSpec: {
            /** Name */
            name: string;
            /** Version */
            version: number;
            /**
             * Param Name
             * @description Tên tham số chính (primary_param.name)
             */
            param_name: string;
            /**
             * Param Unit
             * @description Đơn vị tham số chính (primary_param.unit)
             */
            param_unit: string;
        };
        /**
         * RunCompletion
         * @description Body của `POST /runs/{id}/complete`.
         */
        RunCompletion: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Lease Id
             * Format: uuid
             */
            lease_id: string;
            run_result: components["schemas"]["RunResult"];
            /** Failure Cases */
            failure_cases: components["schemas"]["FailureCaseRecord"][];
        };
        /**
         * RunCounts
         * @description Số run theo từng `RunStatus`.
         */
        RunCounts: {
            /** Queued */
            queued: number;
            /** Running */
            running: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Skipped */
            skipped: number;
            /** Stopped Limit */
            stopped_limit: number;
            /** Cancelled */
            cancelled: number;
        };
        /** RunMetrics */
        RunMetrics: {
            clean: components["schemas"]["MapPair"];
            attacked: components["schemas"]["MapPair"];
            /**
             * Relative Drop
             * @description null khi mAP@0.5 sạch bằng 0
             */
            relative_drop: number | null;
            /** Absolute Drop */
            absolute_drop: number;
            /**
             * Attack Success Rate
             * @description null khi không có object nào được detect đúng trên ảnh sạch (|C| = 0)
             */
            attack_success_rate: number | null;
            /**
             * Per Class
             * @default null
             */
            per_class: {
                [key: string]: components["schemas"]["ClassRunMetrics"];
            } | null;
            /**
             * Partial
             * @description true khi metric chỉ tính trên phần ảnh đã xử lý (stopped_limit)
             * @default false
             */
            partial: boolean;
        };
        /**
         * RunMode
         * @enum {string}
         */
        RunMode: "grid" | "search";
        /** RunResult */
        RunResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            status: components["schemas"]["RunStatus"];
            /** @default null */
            status_reason: components["schemas"]["StatusReason"] | null;
            progress: components["schemas"]["Progress"];
            /** @default null */
            metrics: components["schemas"]["RunMetrics"] | null;
            /** Gpu Seconds */
            gpu_seconds: number;
            /**
             * @description null với máy local
             * @default null
             */
            cost: components["schemas"]["Cost"] | null;
            /** Failure Case Ids */
            failure_case_ids: string[];
            /**
             * Manifest Uri
             * @default null
             */
            manifest_uri: string | null;
            /**
             * Cached From Run Id
             * @description Run gốc khi status = skipped với code = cached (Phase 3)
             * @default null
             */
            cached_from_run_id: string | null;
            /** Fingerprint */
            fingerprint: string;
        };
        /** RunStartRequest */
        RunStartRequest: {
            /**
             * Lease Id
             * Format: uuid
             */
            lease_id: string;
            /** Fingerprint */
            fingerprint: string;
            fingerprint_inputs: components["schemas"]["FingerprintInputs"];
            environment: components["schemas"]["Environment"];
        };
        /** RunStartResponse */
        RunStartResponse: {
            /**
             * Action
             * @enum {string}
             */
            action: "run" | "skip_cached";
            /**
             * Cached From Run Id
             * @description Chỉ có khi skip_cached
             * @default null
             */
            cached_from_run_id: string | null;
            /**
             * @description Kết quả của run gốc (completed); chỉ có khi skip_cached
             * @default null
             */
            cached_result: components["schemas"]["RunResult"] | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed" | "skipped" | "stopped_limit" | "cancelled";
        /**
         * RunView
         * @description Run hiển thị cho người dùng. `fingerprint` null khi và chỉ khi run chưa bắt đầu: worker
         *     tính fingerprint ở `start` (đề xuất contract 001, Phase 5).
         */
        RunView: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            /** Level */
            level: number;
            status: components["schemas"]["RunStatus"];
            /** @default null */
            status_reason: components["schemas"]["StatusReason"] | null;
            progress: components["schemas"]["Progress"];
            /** @default null */
            metrics: components["schemas"]["RunMetrics"] | null;
            /** Gpu Seconds */
            gpu_seconds: number;
            /**
             * @description null với máy local
             * @default null
             */
            cost: components["schemas"]["Cost"] | null;
            /** Failure Case Ids */
            failure_case_ids: string[];
            /**
             * Manifest Uri
             * @default null
             */
            manifest_uri: string | null;
            /**
             * Cached From Run Id
             * @description Run gốc khi status = skipped với code = cached (Phase 3)
             * @default null
             */
            cached_from_run_id: string | null;
            /**
             * Fingerprint
             * @description null khi run chưa bắt đầu (queued, hoặc bị hủy/dừng trước khi chạy)
             */
            fingerprint: string | null;
            attack_spec: components["schemas"]["RunAttackSpec"];
        };
        /** SearchConfig */
        SearchConfig: {
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Tol */
            tol: number;
            /** Coarse N */
            coarse_n: number;
            /** Subset Size */
            subset_size: number;
            /**
             * Class Filter
             * @default null
             */
            class_filter: string[] | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Attack Spec Id
             * Format: uuid
             */
            attack_spec_id: string;
            status: components["schemas"]["SearchStatus"];
            threshold_kind: components["schemas"]["ThresholdKind"];
            /** Threshold */
            threshold: number;
            /**
             * Breaking Point
             * @default null
             */
            breaking_point: number | null;
            /**
             * Bracket
             * @description Khoảng hiện tại, kể cả khi dừng giữa chừng
             */
            bracket: [
                number,
                number
            ];
            /**
             * Confidence Interval
             * @description null nếu chưa tính bootstrap
             * @default null
             */
            confidence_interval: [
                number,
                number
            ] | null;
            /**
             * Near Threshold
             * @description Khoảng tin cậy bao trùm ngưỡng
             */
            near_threshold: boolean;
            /** Trajectory */
            trajectory: components["schemas"]["TrajectoryPoint"][];
        };
        /**
         * SearchStatus
         * @enum {string}
         */
        SearchStatus: "found" | "not_reached" | "below_min" | "stopped_limit" | "non_monotonic";
        /**
         * SkipReason
         * @enum {string}
         */
        SkipReason: "cached" | "incompatible";
        /**
         * SliceFilter
         * @description Bộ lọc tự mô tả, không phụ thuộc model hay mapping.
         */
        SliceFilter: {
            /**
             * Classes
             * @description Class gốc được tính, sắp xếp, không trùng
             */
            classes: string[];
            difficulty: components["schemas"]["DifficultyFilter"] | null;
            /**
             * Min Objects
             * @default 1
             */
            min_objects: number;
        };
        /** SliceRef */
        SliceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
        };
        /** SliceSpec */
        SliceSpec: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Slice Sha256
             * @description sha256 của dataset_version_sha256, filter, seed, size, image_ids
             */
            slice_sha256: string;
            /** Dataset Version Sha256 */
            dataset_version_sha256: string;
            filter: components["schemas"]["SliceFilter"];
            /** Seed */
            seed: number;
            /** Size */
            size: number;
            /**
             * Image Ids
             * @description Sắp xếp, không trùng, đúng size phần tử
             */
            image_ids: string[];
            /**
             * Image Ids Sha256
             * @description sha256_of(image_ids)
             */
            image_ids_sha256: string;
        };
        /** SliceSummary */
        SliceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Dataset Version Id
             * Format: uuid
             */
            dataset_version_id: string;
            /** Slice Sha256 */
            slice_sha256: string | null;
            /** Size */
            size: number;
            /** Seed */
            seed: number;
            /**
             * Classes
             * @description Class gốc được tính (filter.classes)
             */
            classes: string[];
        };
        /** StatusReason */
        StatusReason: {
            /** Code */
            code: components["schemas"]["StopReason"] | components["schemas"]["SkipReason"] | ("error" | "cancelled");
            /** Message */
            message: string;
        };
        /**
         * StopReason
         * @enum {string}
         */
        StopReason: "budget" | "time";
        /**
         * ThresholdKind
         * @enum {string}
         */
        ThresholdKind: "relative_drop" | "absolute_drop" | "attack_success_rate";
        /** Timing */
        Timing: {
            /** Total S */
            total_s: number;
            /** Sec Per Image */
            sec_per_image: number;
        };
        /** TrajectoryPoint */
        TrajectoryPoint: {
            /** Order */
            order: number;
            /** Level */
            level: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "subset" | "full";
            /** Drop */
            drop: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** UserAdminPage */
        UserAdminPage: {
            /** Items */
            items: components["schemas"]["UserAdminView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** UserAdminView */
        UserAdminView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Organization */
            organization: string | null;
            status: components["schemas"]["UserStatus"];
            /** Roles */
            roles: components["schemas"]["Role"][];
            requested_role: components["schemas"]["Role"] | null;
            /** Request Reason */
            request_reason: string | null;
            /**
             * Reject Reason
             * @description Chỉ có khi status = rejected
             */
            reject_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Approved At */
            approved_at: string | null;
            /** Approved By */
            approved_by: string | null;
        };
        /** UserRef */
        UserRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "pending" | "active" | "rejected" | "disabled";
        /** WorkerDirective */
        WorkerDirective: {
            /**
             * Action
             * @enum {string}
             */
            action: "continue" | "cancel" | "stop_limit";
            /**
             * Remaining Seconds
             * @description Thời gian xử lý còn lại; null khi giới hạn là tiền
             */
            remaining_seconds: number | null;
        };
        /**
         * WorkerJobBundle
         * @description Mọi thứ worker cần để chạy một experiment (`GET /experiments/{id}/bundle`).
         */
        WorkerJobBundle: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            config: components["schemas"]["ExperimentConfig"];
            model_card: components["schemas"]["ModelCard"];
            slice: components["schemas"]["SliceSpec"];
            class_mapping: components["schemas"]["ClassMapping"];
            /** Attack Specs */
            attack_specs: components["schemas"]["AttackSpec"][];
            /** @description Thuộc fingerprint (config_sha256) */
            inference_params: components["schemas"]["InferenceParams"];
            /** Failure Cases Per Run */
            failure_cases_per_run: number;
            /**
             * Cost Profiles
             * @description Profile đã có của (target, model, attack); thiếu thì worker calibrate trước
             */
            cost_profiles: components["schemas"]["CostProfile"][];
            downloads: components["schemas"]["BundleDownloads"];
            limit: components["schemas"]["BundleLimit"];
            /**
             * Runs
             * @description Theo thứ tự chạy
             */
            runs: components["schemas"]["BundleRun"][];
        };
        /**
         * WorkerLease
         * @description Trả về từ `POST /lease` (không có job thì `204`).
         */
        WorkerLease: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Lease Id
             * Format: uuid
             * @description Đổi mỗi lần lease; gửi kèm mọi request sau đó
             */
            lease_id: string;
            /**
             * Lease Expires At
             * Format: date-time
             */
            lease_expires_at: string;
        };
        /**
         * Permission
         * @enum {string}
         */
        _P: "experiment.read" | "experiment.create" | "experiment.cancel_own" | "experiment.submit_review" | "dataset.read" | "dataset.upload" | "slice.create" | "model.read" | "model.manage" | "attack_catalog.read" | "attack_catalog.manage" | "protocol.read" | "protocol.manage" | "review.decide" | "report.export" | "report.read" | "user.manage" | "compute_target.read" | "compute_target.manage" | "budget.manage" | "audit.read";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AccessRequest = components['schemas']['AccessRequest'];
export type ApproveRequest = components['schemas']['ApproveRequest'];
export type ArtifactUrlRequest = components['schemas']['ArtifactUrlRequest'];
export type ArtifactUrlResponse = components['schemas']['ArtifactUrlResponse'];
export type AttackAccess = components['schemas']['AttackAccess'];
export type AttackConfig = components['schemas']['AttackConfig'];
export type AttackKind = components['schemas']['AttackKind'];
export type AttackSpec = components['schemas']['AttackSpec'];
export type AuditActor = components['schemas']['AuditActor'];
export type AuditLogEntry = components['schemas']['AuditLogEntry'];
export type AuditLogPage = components['schemas']['AuditLogPage'];
export type BillingMode = components['schemas']['BillingMode'];
export type BundleCheckpoint = components['schemas']['BundleCheckpoint'];
export type BundleDownloads = components['schemas']['BundleDownloads'];
export type BundleLimit = components['schemas']['BundleLimit'];
export type BundleRun = components['schemas']['BundleRun'];
export type CacheInfo = components['schemas']['CacheInfo'];
export type CaseArtifacts = components['schemas']['CaseArtifacts'];
export type CaseBox = components['schemas']['CaseBox'];
export type CaseDetections = components['schemas']['CaseDetections'];
export type CaseIgnoreRegion = components['schemas']['CaseIgnoreRegion'];
export type CaseSeverity = components['schemas']['CaseSeverity'];
export type ClassEvalMetrics = components['schemas']['ClassEvalMetrics'];
export type ClassMapping = components['schemas']['ClassMapping'];
export type ClassMappingSummary = components['schemas']['ClassMappingSummary'];
export type ClassRunMetrics = components['schemas']['ClassRunMetrics'];
export type CleanEvalResult = components['schemas']['CleanEvalResult'];
export type CloneWarning = components['schemas']['CloneWarning'];
export type ComputeKind = components['schemas']['ComputeKind'];
export type ComputeTargetPublic = components['schemas']['ComputeTargetPublic'];
export type ComputeTargetRef = components['schemas']['ComputeTargetRef'];
export type ConverterInfo = components['schemas']['ConverterInfo'];
export type Cost = components['schemas']['Cost'];
export type CostModel = components['schemas']['CostModel'];
export type CostProfile = components['schemas']['CostProfile'];
export type DatasetManifest = components['schemas']['DatasetManifest'];
export type DatasetSummary = components['schemas']['DatasetSummary'];
export type DatasetVersionSummary = components['schemas']['DatasetVersionSummary'];
export type DependencyStatus = components['schemas']['DependencyStatus'];
export type DifficultyFilter = components['schemas']['DifficultyFilter'];
export type DisplayMode = components['schemas']['DisplayMode'];
export type Environment = components['schemas']['Environment'];
export type ErrorBody = components['schemas']['ErrorBody'];
export type ErrorCode = components['schemas']['ErrorCode'];
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type EstimateResponse = components['schemas']['EstimateResponse'];
export type EstimateRun = components['schemas']['EstimateRun'];
export type EvalMappingRef = components['schemas']['EvalMappingRef'];
export type EvalMetrics = components['schemas']['EvalMetrics'];
export type EvalModelRef = components['schemas']['EvalModelRef'];
export type EvalSliceRef = components['schemas']['EvalSliceRef'];
export type ExperimentClone = components['schemas']['ExperimentClone'];
export type ExperimentConfig = components['schemas']['ExperimentConfig'];
export type ExperimentCreate = components['schemas']['ExperimentCreate'];
export type ExperimentDetail = components['schemas']['ExperimentDetail'];
export type ExperimentPage = components['schemas']['ExperimentPage'];
export type ExperimentStatus = components['schemas']['ExperimentStatus'];
export type ExperimentSummary = components['schemas']['ExperimentSummary'];
export type FailureCaseRecord = components['schemas']['FailureCaseRecord'];
export type FailureCaseUrls = components['schemas']['FailureCaseUrls'];
export type FailureCaseView = components['schemas']['FailureCaseView'];
export type FieldError = components['schemas']['FieldError'];
export type FingerprintInputs = components['schemas']['FingerprintInputs'];
export type GradientCheck = components['schemas']['GradientCheck'];
export type GridConfig = components['schemas']['GridConfig'];
export type HealthResponse = components['schemas']['HealthResponse'];
export type HeartbeatRequest = components['schemas']['HeartbeatRequest'];
export type IgnoreRegion = components['schemas']['IgnoreRegion'];
export type InferenceParams = components['schemas']['InferenceParams'];
export type JsonValue = components['schemas']['JsonValue'];
export type LibVersions = components['schemas']['LibVersions'];
export type Limit = components['schemas']['Limit'];
export type LimitKind = components['schemas']['LimitKind'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type Manifest = components['schemas']['Manifest'];
export type ManifestAnnotation = components['schemas']['ManifestAnnotation'];
export type ManifestImage = components['schemas']['ManifestImage'];
export type ManifestSource = components['schemas']['ManifestSource'];
export type MapPair = components['schemas']['MapPair'];
export type Me = components['schemas']['Me'];
export type ModelCard = components['schemas']['ModelCard'];
export type ModelRef = components['schemas']['ModelRef'];
export type ModelSummary = components['schemas']['ModelSummary'];
export type PassCriterion = components['schemas']['PassCriterion'];
export type PasswordChange = components['schemas']['PasswordChange'];
export type PasswordResetConsume = components['schemas']['PasswordResetConsume'];
export type PasswordResetLink = components['schemas']['PasswordResetLink'];
export type Permission = components['schemas']['Permission'];
export type PrimaryParam = components['schemas']['PrimaryParam'];
export type Progress = components['schemas']['Progress'];
export type ProgressReport = components['schemas']['ProgressReport'];
export type ProtocolBody = components['schemas']['ProtocolBody'];
export type ProtocolRef = components['schemas']['ProtocolRef'];
export type ProtocolStatus = components['schemas']['ProtocolStatus'];
export type ProtocolSummary = components['schemas']['ProtocolSummary'];
export type QueueEstimate = components['schemas']['QueueEstimate'];
export type RejectRequest = components['schemas']['RejectRequest'];
export type RequiredAttack = components['schemas']['RequiredAttack'];
export type ReviewDecision = components['schemas']['ReviewDecision'];
export type Role = components['schemas']['Role'];
export type RolesUpdate = components['schemas']['RolesUpdate'];
export type RunAttackSpec = components['schemas']['RunAttackSpec'];
export type RunCompletion = components['schemas']['RunCompletion'];
export type RunCounts = components['schemas']['RunCounts'];
export type RunMetrics = components['schemas']['RunMetrics'];
export type RunMode = components['schemas']['RunMode'];
export type RunResult = components['schemas']['RunResult'];
export type RunStartRequest = components['schemas']['RunStartRequest'];
export type RunStartResponse = components['schemas']['RunStartResponse'];
export type RunStatus = components['schemas']['RunStatus'];
export type RunView = components['schemas']['RunView'];
export type SearchConfig = components['schemas']['SearchConfig'];
export type SearchResult = components['schemas']['SearchResult'];
export type SearchStatus = components['schemas']['SearchStatus'];
export type SkipReason = components['schemas']['SkipReason'];
export type SliceFilter = components['schemas']['SliceFilter'];
export type SliceRef = components['schemas']['SliceRef'];
export type SliceSpec = components['schemas']['SliceSpec'];
export type SliceSummary = components['schemas']['SliceSummary'];
export type StatusReason = components['schemas']['StatusReason'];
export type StopReason = components['schemas']['StopReason'];
export type ThresholdKind = components['schemas']['ThresholdKind'];
export type Timing = components['schemas']['Timing'];
export type TrajectoryPoint = components['schemas']['TrajectoryPoint'];
export type UserAdminPage = components['schemas']['UserAdminPage'];
export type UserAdminView = components['schemas']['UserAdminView'];
export type UserRef = components['schemas']['UserRef'];
export type UserStatus = components['schemas']['UserStatus'];
export type WorkerDirective = components['schemas']['WorkerDirective'];
export type WorkerJobBundle = components['schemas']['WorkerJobBundle'];
export type WorkerLease = components['schemas']['WorkerLease'];
export type P = components['schemas']['_P'];
export type $defs = Record<string, never>;
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const artifactUrlRequestMethodValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ArtifactUrlRequest"]["method"]> = ["PUT", "GET", "DELETE"];
export const artifactUrlResponseMethodValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ArtifactUrlResponse"]["method"]> = ["PUT", "GET", "DELETE"];
export const attackAccessValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AttackAccess"]> = ["white_box", "black_box"];
export const attackKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AttackKind"]> = ["attack", "corruption", "occlusion"];
export const billingModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["BillingMode"]> = ["none", "hourly"];
export const caseSeverityValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CaseSeverity"]> = ["critical", "major", "minor", "acceptable"];
export const computeKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ComputeKind"]> = ["local", "rented"];
export const displayModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["DisplayMode"]> = ["normal", "hidden_unanonymized", "dev_unblurred"];
export const errorCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ErrorCode"]> = ["not_implemented", "unauthenticated", "forbidden", "not_found", "conflict", "invalid_request", "invalid_credentials", "account_pending", "account_rejected", "account_disabled", "rate_limited", "csrf_failed", "validation_error", "not_supported_yet", "queue_limit_reached", "internal_error"];
export const experimentStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ExperimentStatus"]> = ["draft", "queued", "running", "completed", "submitted_for_review", "in_review", "approved", "changes_requested", "rejected", "cancelled"];
export const healthResponseStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HealthResponse"]["status"]> = ["ok", "degraded"];
export const limitKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["LimitKind"]> = ["budget", "time"];
export const manifestSourceFormatValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ManifestSource"]["format"]> = ["kitti", "yolo", "coco"];
export const modelCardFrameworkValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ModelCard"]["framework"]> = ["ultralytics", "torchvision"];
export const permissionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Permission"]> = ["experiment.read", "experiment.create", "experiment.cancel_own", "experiment.submit_review", "dataset.read", "dataset.upload", "slice.create", "model.read", "model.manage", "attack_catalog.read", "attack_catalog.manage", "protocol.read", "protocol.manage", "review.decide", "report.export", "report.read", "user.manage", "compute_target.read", "compute_target.manage", "budget.manage", "audit.read"];
export const primaryParamTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["PrimaryParam"]["type"]> = ["continuous", "discrete"];
export const protocolStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ProtocolStatus"]> = ["active", "retired", "dev"];
export const reviewDecisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ReviewDecision"]> = ["approve", "changes_requested", "reject"];
export const roleValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Role"]> = ["engineer", "reviewer", "admin"];
export const runModeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RunMode"]> = ["grid", "search"];
export const runStartResponseActionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RunStartResponse"]["action"]> = ["run", "skip_cached"];
export const runStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["RunStatus"]> = ["queued", "running", "completed", "failed", "skipped", "stopped_limit", "cancelled"];
export const searchStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SearchStatus"]> = ["found", "not_reached", "below_min", "stopped_limit", "non_monotonic"];
export const skipReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SkipReason"]> = ["cached", "incompatible"];
export const statusReasonCodeAnyOf2Values: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StatusReason"]["code"]> = ["error", "cancelled"];
export const stopReasonValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["StopReason"]> = ["budget", "time"];
export const thresholdKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ThresholdKind"]> = ["relative_drop", "absolute_drop", "attack_success_rate"];
export const trajectoryPointScopeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["TrajectoryPoint"]["scope"]> = ["subset", "full"];
export const userStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["UserStatus"]> = ["pending", "active", "rejected", "disabled"];
export const workerDirectiveActionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["WorkerDirective"]["action"]> = ["continue", "cancel", "stop_limit"];
export const _PValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["_P"]> = ["experiment.read", "experiment.create", "experiment.cancel_own", "experiment.submit_review", "dataset.read", "dataset.upload", "slice.create", "model.read", "model.manage", "attack_catalog.read", "attack_catalog.manage", "protocol.read", "protocol.manage", "review.decide", "report.export", "report.read", "user.manage", "compute_target.read", "compute_target.manage", "budget.manage", "audit.read"];
export type operations = Record<string, never>;
